POST http://localhost:3030/workflow/register
Content-Type: application/json

{
  "operator": {
    "type": "projection",
    "params": {
      "src_crs": "EPSG:4326",
      "dest_crs": "EPSG:3857"
    },
    "sources": {
      "rasters": [
        {
          "type": "gdal_source",
          "params": {
            "source_name": "test",
            "channel": 0
          }
        }
      ]
    }
  }
}

###

GET http://localhost:3030/workflow/d8086293-1d7f-46c7-9e38-4965b3799fe1
Accept: application/json

###

GET http://localhost:3030/workflow/1
Accept: application/json

###
