POST http://localhost:3030/workflow/register
Content-Type: application/json

{
  "type": "projection",
  "params": {
    "src_crs": "EPSG:4326",
    "dest_crs": "EPSG:3857"
  },
  "sources": {
    "rasters": [
      {
        "type": "gdal_source",
        "params": {
          "source_name": "test",
          "channel": 0
        }
      }
    ]
  }
}

###

GET http://localhost:3030/workflow/0
Accept: application/json

###

GET http://localhost:3030/workflow/1
Accept: application/json

###
