/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AccessConstraints = {
    Unclassified: 'unclassified',
    Restricted: 'restricted',
    Confidential: 'confidential',
    Secret: 'secret',
    TopSecret: 'topSecret'
} as const;
export type AccessConstraints = typeof AccessConstraints[keyof typeof AccessConstraints];


export function instanceOfAccessConstraints(value: any): boolean {
    for (const key in AccessConstraints) {
        if (Object.prototype.hasOwnProperty.call(AccessConstraints, key)) {
            if (AccessConstraints[key as keyof typeof AccessConstraints] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccessConstraintsFromJSON(json: any): AccessConstraints {
    return AccessConstraintsFromJSONTyped(json, false);
}

export function AccessConstraintsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessConstraints {
    return json as AccessConstraints;
}

export function AccessConstraintsToJSON(value?: AccessConstraints | null): any {
    return value as any;
}

export function AccessConstraintsToJSONTyped(value: any, ignoreDiscriminator: boolean): AccessConstraints {
    return value as AccessConstraints;
}

