/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type BandsByNameOrIndex
 * 
 * @export
 */
export type BandsByNameOrIndex = Array<number> | Array<string>;

export function BandsByNameOrIndexFromJSON(json: any): BandsByNameOrIndex {
    return BandsByNameOrIndexFromJSONTyped(json, false);
}

export function BandsByNameOrIndexFromJSONTyped(json: any, ignoreDiscriminator: boolean): BandsByNameOrIndex {
    if (json == null) {
        return json;
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'string')) {
            return json;
        }
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'number')) {
            return json;
        }
    }
    return {} as any;
}

export function BandsByNameOrIndexToJSON(json: any): any {
    return BandsByNameOrIndexToJSONTyped(json, false);
}

export function BandsByNameOrIndexToJSONTyped(value?: BandsByNameOrIndex | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'string')) {
            return value;
        }
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'number')) {
            return value;
        }
    }
    return {};
}

