/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The parameter spec for `ClassHistogram`.
 * @export
 * @interface ClassHistogramParameters
 */
export interface ClassHistogramParameters {
    /**
     * The name of the attribute making up the x-axis of the histogram.
     * Must be set for a vector sources, must not be set for rasters.
     * @type {string}
     * @memberof ClassHistogramParameters
     */
    columnName?: string | null;
}

/**
 * Check if a given object implements the ClassHistogramParameters interface.
 */
export function instanceOfClassHistogramParameters(value: object): value is ClassHistogramParameters {
    return true;
}

export function ClassHistogramParametersFromJSON(json: any): ClassHistogramParameters {
    return ClassHistogramParametersFromJSONTyped(json, false);
}

export function ClassHistogramParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassHistogramParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'columnName': json['columnName'] == null ? undefined : json['columnName'],
    };
}

export function ClassHistogramParametersToJSON(json: any): ClassHistogramParameters {
    return ClassHistogramParametersToJSONTyped(json, false);
}

export function ClassHistogramParametersToJSONTyped(value?: ClassHistogramParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columnName': value['columnName'],
    };
}

