/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SingleVectorSource } from './SingleVectorSource';
import {
    SingleVectorSourceFromJSON,
    SingleVectorSourceFromJSONTyped,
    SingleVectorSourceToJSON,
    SingleVectorSourceToJSONTyped,
} from './SingleVectorSource';
import type { ColumnRangeFilterParameters } from './ColumnRangeFilterParameters';
import {
    ColumnRangeFilterParametersFromJSON,
    ColumnRangeFilterParametersFromJSONTyped,
    ColumnRangeFilterParametersToJSON,
    ColumnRangeFilterParametersToJSONTyped,
} from './ColumnRangeFilterParameters';

/**
 * The `ColumnRangeFilter` operator allows filtering `FeatureCollection`s.
 * Users can define one or more data ranges for a column in the data table that is then filtered.
 * The filter can be used for numerical as well as textual columns.
 * Each range is inclusive, i.e. `[start, end]` includes both the `start` and the `end` values.
 * 
 * ## Errors
 * 
 * If the value in the `column` parameter is not a column of the feature collection, an error is thrown.
 * @export
 * @interface ColumnRangeFilter
 */
export interface ColumnRangeFilter {
    /**
     * 
     * @type {ColumnRangeFilterTypeEnum}
     * @memberof ColumnRangeFilter
     */
    type: ColumnRangeFilterTypeEnum;
    /**
     * 
     * @type {ColumnRangeFilterParameters}
     * @memberof ColumnRangeFilter
     */
    params: ColumnRangeFilterParameters;
    /**
     * 
     * @type {SingleVectorSource}
     * @memberof ColumnRangeFilter
     */
    sources: SingleVectorSource;
}


/**
 * @export
 */
export const ColumnRangeFilterTypeEnum = {
    ColumnRangeFilter: 'ColumnRangeFilter'
} as const;
export type ColumnRangeFilterTypeEnum = typeof ColumnRangeFilterTypeEnum[keyof typeof ColumnRangeFilterTypeEnum];


/**
 * Check if a given object implements the ColumnRangeFilter interface.
 */
export function instanceOfColumnRangeFilter(value: object): value is ColumnRangeFilter {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    if (!('sources' in value) || value['sources'] === undefined) return false;
    return true;
}

export function ColumnRangeFilterFromJSON(json: any): ColumnRangeFilter {
    return ColumnRangeFilterFromJSONTyped(json, false);
}

export function ColumnRangeFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnRangeFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'params': ColumnRangeFilterParametersFromJSON(json['params']),
        'sources': SingleVectorSourceFromJSON(json['sources']),
    };
}

export function ColumnRangeFilterToJSON(json: any): ColumnRangeFilter {
    return ColumnRangeFilterToJSONTyped(json, false);
}

export function ColumnRangeFilterToJSONTyped(value?: ColumnRangeFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'params': ColumnRangeFilterParametersToJSON(value['params']),
        'sources': SingleVectorSourceToJSON(value['sources']),
    };
}

