/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataUsageSummary
 */
export interface DataUsageSummary {
    /**
     * 
     * @type {number}
     * @memberof DataUsageSummary
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof DataUsageSummary
     */
    data: string;
    /**
     * 
     * @type {Date}
     * @memberof DataUsageSummary
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the DataUsageSummary interface.
 */
export function instanceOfDataUsageSummary(value: object): value is DataUsageSummary {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function DataUsageSummaryFromJSON(json: any): DataUsageSummary {
    return DataUsageSummaryFromJSONTyped(json, false);
}

export function DataUsageSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataUsageSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'data': json['data'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function DataUsageSummaryToJSON(json: any): DataUsageSummary {
    return DataUsageSummaryToJSONTyped(json, false);
}

export function DataUsageSummaryToJSONTyped(value?: DataUsageSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'data': value['data'],
        'timestamp': value['timestamp'].toISOString(),
    };
}

