/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetaDataDefinition } from './MetaDataDefinition';
import {
    MetaDataDefinitionFromJSON,
    MetaDataDefinitionFromJSONTyped,
    MetaDataDefinitionToJSON,
    MetaDataDefinitionToJSONTyped,
} from './MetaDataDefinition';
import type { AddDataset } from './AddDataset';
import {
    AddDatasetFromJSON,
    AddDatasetFromJSONTyped,
    AddDatasetToJSON,
    AddDatasetToJSONTyped,
} from './AddDataset';

/**
 * 
 * @export
 * @interface DatasetDefinition
 */
export interface DatasetDefinition {
    /**
     * 
     * @type {AddDataset}
     * @memberof DatasetDefinition
     */
    properties: AddDataset;
    /**
     * 
     * @type {MetaDataDefinition}
     * @memberof DatasetDefinition
     */
    metaData: MetaDataDefinition;
}

/**
 * Check if a given object implements the DatasetDefinition interface.
 */
export function instanceOfDatasetDefinition(value: object): value is DatasetDefinition {
    if (!('properties' in value) || value['properties'] === undefined) return false;
    if (!('metaData' in value) || value['metaData'] === undefined) return false;
    return true;
}

export function DatasetDefinitionFromJSON(json: any): DatasetDefinition {
    return DatasetDefinitionFromJSONTyped(json, false);
}

export function DatasetDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'properties': AddDatasetFromJSON(json['properties']),
        'metaData': MetaDataDefinitionFromJSON(json['metaData']),
    };
}

export function DatasetDefinitionToJSON(json: any): DatasetDefinition {
    return DatasetDefinitionToJSONTyped(json, false);
}

export function DatasetDefinitionToJSONTyped(value?: DatasetDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'properties': AddDatasetToJSON(value['properties']),
        'metaData': MetaDataDefinitionToJSON(value['metaData']),
    };
}

