/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasetLayerListingCollection } from './DatasetLayerListingCollection';
import {
    DatasetLayerListingCollectionFromJSON,
    DatasetLayerListingCollectionFromJSONTyped,
    DatasetLayerListingCollectionToJSON,
    DatasetLayerListingCollectionToJSONTyped,
} from './DatasetLayerListingCollection';

/**
 * 
 * @export
 * @interface DatasetLayerListingProviderDefinition
 */
export interface DatasetLayerListingProviderDefinition {
    /**
     * 
     * @type {DatasetLayerListingProviderDefinitionTypeEnum}
     * @memberof DatasetLayerListingProviderDefinition
     */
    type: DatasetLayerListingProviderDefinitionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DatasetLayerListingProviderDefinition
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetLayerListingProviderDefinition
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetLayerListingProviderDefinition
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof DatasetLayerListingProviderDefinition
     */
    priority?: number | null;
    /**
     * 
     * @type {Array<DatasetLayerListingCollection>}
     * @memberof DatasetLayerListingProviderDefinition
     */
    collections: Array<DatasetLayerListingCollection>;
}


/**
 * @export
 */
export const DatasetLayerListingProviderDefinitionTypeEnum = {
    DatasetLayerListing: 'DatasetLayerListing'
} as const;
export type DatasetLayerListingProviderDefinitionTypeEnum = typeof DatasetLayerListingProviderDefinitionTypeEnum[keyof typeof DatasetLayerListingProviderDefinitionTypeEnum];


/**
 * Check if a given object implements the DatasetLayerListingProviderDefinition interface.
 */
export function instanceOfDatasetLayerListingProviderDefinition(value: object): value is DatasetLayerListingProviderDefinition {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('collections' in value) || value['collections'] === undefined) return false;
    return true;
}

export function DatasetLayerListingProviderDefinitionFromJSON(json: any): DatasetLayerListingProviderDefinition {
    return DatasetLayerListingProviderDefinitionFromJSONTyped(json, false);
}

export function DatasetLayerListingProviderDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetLayerListingProviderDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'collections': ((json['collections'] as Array<any>).map(DatasetLayerListingCollectionFromJSON)),
    };
}

export function DatasetLayerListingProviderDefinitionToJSON(json: any): DatasetLayerListingProviderDefinition {
    return DatasetLayerListingProviderDefinitionToJSONTyped(json, false);
}

export function DatasetLayerListingProviderDefinitionToJSONTyped(value?: DatasetLayerListingProviderDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'priority': value['priority'],
        'collections': ((value['collections'] as Array<any>).map(DatasetLayerListingCollectionToJSON)),
    };
}

