/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Symbology } from './Symbology';
import {
    SymbologyFromJSON,
    SymbologyFromJSONTyped,
    SymbologyToJSON,
    SymbologyToJSONTyped,
} from './Symbology';
import type { TypedResultDescriptor } from './TypedResultDescriptor';
import {
    TypedResultDescriptorFromJSON,
    TypedResultDescriptorFromJSONTyped,
    TypedResultDescriptorToJSON,
    TypedResultDescriptorToJSONTyped,
} from './TypedResultDescriptor';

/**
 * 
 * @export
 * @interface DatasetListing
 */
export interface DatasetListing {
    /**
     * 
     * @type {string}
     * @memberof DatasetListing
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetListing
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetListing
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetListing
     */
    name: string;
    /**
     * 
     * @type {TypedResultDescriptor}
     * @memberof DatasetListing
     */
    resultDescriptor: TypedResultDescriptor;
    /**
     * 
     * @type {string}
     * @memberof DatasetListing
     */
    sourceOperator: string;
    /**
     * 
     * @type {Symbology}
     * @memberof DatasetListing
     */
    symbology?: Symbology | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DatasetListing
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the DatasetListing interface.
 */
export function instanceOfDatasetListing(value: object): value is DatasetListing {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('resultDescriptor' in value) || value['resultDescriptor'] === undefined) return false;
    if (!('sourceOperator' in value) || value['sourceOperator'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function DatasetListingFromJSON(json: any): DatasetListing {
    return DatasetListingFromJSONTyped(json, false);
}

export function DatasetListingFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetListing {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'displayName': json['displayName'],
        'id': json['id'],
        'name': json['name'],
        'resultDescriptor': TypedResultDescriptorFromJSON(json['resultDescriptor']),
        'sourceOperator': json['sourceOperator'],
        'symbology': json['symbology'] == null ? undefined : SymbologyFromJSON(json['symbology']),
        'tags': json['tags'],
    };
}

export function DatasetListingToJSON(json: any): DatasetListing {
    return DatasetListingToJSONTyped(json, false);
}

export function DatasetListingToJSONTyped(value?: DatasetListing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'displayName': value['displayName'],
        'id': value['id'],
        'name': value['name'],
        'resultDescriptor': TypedResultDescriptorToJSON(value['resultDescriptor']),
        'sourceOperator': value['sourceOperator'],
        'symbology': SymbologyToJSON(value['symbology']),
        'tags': value['tags'],
    };
}

