/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Scaling factor in x/y direction.
 * @export
 * @interface Fraction
 */
export interface Fraction {
    /**
     * 
     * @type {number}
     * @memberof Fraction
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof Fraction
     */
    y: number;
    /**
     * 
     * @type {FractionTypeEnum}
     * @memberof Fraction
     */
    type: FractionTypeEnum;
}


/**
 * @export
 */
export const FractionTypeEnum = {
    Fraction: 'fraction'
} as const;
export type FractionTypeEnum = typeof FractionTypeEnum[keyof typeof FractionTypeEnum];


/**
 * Check if a given object implements the Fraction interface.
 */
export function instanceOfFraction(value: object): value is Fraction {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FractionFromJSON(json: any): Fraction {
    return FractionFromJSONTyped(json, false);
}

export function FractionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Fraction {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
        'type': json['type'],
    };
}

export function FractionToJSON(json: any): Fraction {
    return FractionToJSONTyped(json, false);
}

export function FractionToJSONTyped(value?: Fraction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
        'type': value['type'],
    };
}

