/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GdalMetadataMapping } from './GdalMetadataMapping';
import {
    GdalMetadataMappingFromJSON,
    GdalMetadataMappingFromJSONTyped,
    GdalMetadataMappingToJSON,
    GdalMetadataMappingToJSONTyped,
} from './GdalMetadataMapping';
import type { FileNotFoundHandling } from './FileNotFoundHandling';
import {
    FileNotFoundHandlingFromJSON,
    FileNotFoundHandlingFromJSONTyped,
    FileNotFoundHandlingToJSON,
    FileNotFoundHandlingToJSONTyped,
} from './FileNotFoundHandling';
import type { GeoTransform } from './GeoTransform';
import {
    GeoTransformFromJSON,
    GeoTransformFromJSONTyped,
    GeoTransformToJSON,
    GeoTransformToJSONTyped,
} from './GeoTransform';

/**
 * Parameters for loading data using Gdal
 * @export
 * @interface GdalDatasetParameters
 */
export interface GdalDatasetParameters {
    /**
     * 
     * @type {string}
     * @memberof GdalDatasetParameters
     */
    filePath: string;
    /**
     * 
     * @type {number}
     * @memberof GdalDatasetParameters
     */
    rasterbandChannel: number;
    /**
     * 
     * @type {GeoTransform}
     * @memberof GdalDatasetParameters
     */
    geoTransform: GeoTransform;
    /**
     * 
     * @type {number}
     * @memberof GdalDatasetParameters
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof GdalDatasetParameters
     */
    height: number;
    /**
     * 
     * @type {FileNotFoundHandling}
     * @memberof GdalDatasetParameters
     */
    fileNotFoundHandling: FileNotFoundHandling;
    /**
     * 
     * @type {number}
     * @memberof GdalDatasetParameters
     */
    noDataValue?: number | null;
    /**
     * 
     * @type {Array<GdalMetadataMapping>}
     * @memberof GdalDatasetParameters
     */
    propertiesMapping?: Array<GdalMetadataMapping> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GdalDatasetParameters
     */
    gdalOpenOptions?: Array<string> | null;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof GdalDatasetParameters
     */
    gdalConfigOptions?: Array<Array<string>> | null;
    /**
     * 
     * @type {boolean}
     * @memberof GdalDatasetParameters
     */
    allowAlphabandAsMask?: boolean;
}



/**
 * Check if a given object implements the GdalDatasetParameters interface.
 */
export function instanceOfGdalDatasetParameters(value: object): value is GdalDatasetParameters {
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    if (!('rasterbandChannel' in value) || value['rasterbandChannel'] === undefined) return false;
    if (!('geoTransform' in value) || value['geoTransform'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('fileNotFoundHandling' in value) || value['fileNotFoundHandling'] === undefined) return false;
    return true;
}

export function GdalDatasetParametersFromJSON(json: any): GdalDatasetParameters {
    return GdalDatasetParametersFromJSONTyped(json, false);
}

export function GdalDatasetParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GdalDatasetParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'filePath': json['filePath'],
        'rasterbandChannel': json['rasterbandChannel'],
        'geoTransform': GeoTransformFromJSON(json['geoTransform']),
        'width': json['width'],
        'height': json['height'],
        'fileNotFoundHandling': FileNotFoundHandlingFromJSON(json['fileNotFoundHandling']),
        'noDataValue': json['noDataValue'] == null ? undefined : json['noDataValue'],
        'propertiesMapping': json['propertiesMapping'] == null ? undefined : ((json['propertiesMapping'] as Array<any>).map(GdalMetadataMappingFromJSON)),
        'gdalOpenOptions': json['gdalOpenOptions'] == null ? undefined : json['gdalOpenOptions'],
        'gdalConfigOptions': json['gdalConfigOptions'] == null ? undefined : json['gdalConfigOptions'],
        'allowAlphabandAsMask': json['allowAlphabandAsMask'] == null ? undefined : json['allowAlphabandAsMask'],
    };
}

export function GdalDatasetParametersToJSON(json: any): GdalDatasetParameters {
    return GdalDatasetParametersToJSONTyped(json, false);
}

export function GdalDatasetParametersToJSONTyped(value?: GdalDatasetParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filePath': value['filePath'],
        'rasterbandChannel': value['rasterbandChannel'],
        'geoTransform': GeoTransformToJSON(value['geoTransform']),
        'width': value['width'],
        'height': value['height'],
        'fileNotFoundHandling': FileNotFoundHandlingToJSON(value['fileNotFoundHandling']),
        'noDataValue': value['noDataValue'],
        'propertiesMapping': value['propertiesMapping'] == null ? undefined : ((value['propertiesMapping'] as Array<any>).map(GdalMetadataMappingToJSON)),
        'gdalOpenOptions': value['gdalOpenOptions'],
        'gdalConfigOptions': value['gdalConfigOptions'],
        'allowAlphabandAsMask': value['allowAlphabandAsMask'],
    };
}

