/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RasterResultDescriptor } from './RasterResultDescriptor';
import {
    RasterResultDescriptorFromJSON,
    RasterResultDescriptorFromJSONTyped,
    RasterResultDescriptorToJSON,
    RasterResultDescriptorToJSONTyped,
} from './RasterResultDescriptor';
import type { ZRole } from './ZRole';
import {
    ZRoleFromJSON,
    ZRoleFromJSONTyped,
    ZRoleToJSON,
    ZRoleToJSONTyped,
} from './ZRole';

/**
 * 
 * @export
 * @interface GdalMdMetaData
 */
export interface GdalMdMetaData {
    /**
     * 
     * @type {GdalMdMetaDataTypeEnum}
     * @memberof GdalMdMetaData
     */
    type: GdalMdMetaDataTypeEnum;
    /**
     * 
     * @type {RasterResultDescriptor}
     * @memberof GdalMdMetaData
     */
    resultDescriptor: RasterResultDescriptor;
    /**
     * 
     * @type {ZRole}
     * @memberof GdalMdMetaData
     */
    zRole: ZRole;
    /**
     * whether the stored 0..360 degree coverage is re-presented as -180..180
     * @type {boolean}
     * @memberof GdalMdMetaData
     */
    wrap: boolean;
    /**
     * upper bound on the z slices a single worker read may request; `None` means the
     * operator's default. A dataset property, since a batch is sized against the slice
     * size of the data itself.
     * @type {number}
     * @memberof GdalMdMetaData
     */
    maxZBatchSize?: number | null;
    /**
     * Dataset-level TTL fallback used when no tile-level TTL is provided.
     * @type {number}
     * @memberof GdalMdMetaData
     */
    cacheTtl?: number | null;
    /**
     * Fixed index into each dimension between z and (y, x), so one dataset is one slice of
     * a 4D array - `[depth]` for `(time, depth, y, x)`. Empty for 3D.
     * @type {Array<number>}
     * @memberof GdalMdMetaData
     */
    leadingPrefix?: Array<number>;
}


/**
 * @export
 */
export const GdalMdMetaDataTypeEnum = {
    GdalMdMetaData: 'GdalMdMetaData'
} as const;
export type GdalMdMetaDataTypeEnum = typeof GdalMdMetaDataTypeEnum[keyof typeof GdalMdMetaDataTypeEnum];


/**
 * Check if a given object implements the GdalMdMetaData interface.
 */
export function instanceOfGdalMdMetaData(value: object): value is GdalMdMetaData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('resultDescriptor' in value) || value['resultDescriptor'] === undefined) return false;
    if (!('zRole' in value) || value['zRole'] === undefined) return false;
    if (!('wrap' in value) || value['wrap'] === undefined) return false;
    return true;
}

export function GdalMdMetaDataFromJSON(json: any): GdalMdMetaData {
    return GdalMdMetaDataFromJSONTyped(json, false);
}

export function GdalMdMetaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GdalMdMetaData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'resultDescriptor': RasterResultDescriptorFromJSON(json['resultDescriptor']),
        'zRole': ZRoleFromJSON(json['zRole']),
        'wrap': json['wrap'],
        'maxZBatchSize': json['maxZBatchSize'] == null ? undefined : json['maxZBatchSize'],
        'cacheTtl': json['cacheTtl'] == null ? undefined : json['cacheTtl'],
        'leadingPrefix': json['leadingPrefix'] == null ? undefined : json['leadingPrefix'],
    };
}

export function GdalMdMetaDataToJSON(json: any): GdalMdMetaData {
    return GdalMdMetaDataToJSONTyped(json, false);
}

export function GdalMdMetaDataToJSONTyped(value?: GdalMdMetaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'resultDescriptor': RasterResultDescriptorToJSON(value['resultDescriptor']),
        'zRole': ZRoleToJSON(value['zRole']),
        'wrap': value['wrap'],
        'maxZBatchSize': value['maxZBatchSize'],
        'cacheTtl': value['cacheTtl'],
        'leadingPrefix': value['leadingPrefix'],
    };
}

