/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistogramBoundsValues
 */
export interface HistogramBoundsValues {
    /**
     * 
     * @type {number}
     * @memberof HistogramBoundsValues
     */
    min: number;
    /**
     * 
     * @type {number}
     * @memberof HistogramBoundsValues
     */
    max: number;
}

/**
 * Check if a given object implements the HistogramBoundsValues interface.
 */
export function instanceOfHistogramBoundsValues(value: object): value is HistogramBoundsValues {
    if (!('min' in value) || value['min'] === undefined) return false;
    if (!('max' in value) || value['max'] === undefined) return false;
    return true;
}

export function HistogramBoundsValuesFromJSON(json: any): HistogramBoundsValues {
    return HistogramBoundsValuesFromJSONTyped(json, false);
}

export function HistogramBoundsValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistogramBoundsValues {
    if (json == null) {
        return json;
    }
    return {
        
        'min': json['min'],
        'max': json['max'],
    };
}

export function HistogramBoundsValuesToJSON(json: any): HistogramBoundsValues {
    return HistogramBoundsValuesToJSONTyped(json, false);
}

export function HistogramBoundsValuesToJSONTyped(value?: HistogramBoundsValues | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min': value['min'],
        'max': value['max'],
    };
}

