/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HistogramBounds } from './HistogramBounds';
import {
    HistogramBoundsFromJSON,
    HistogramBoundsFromJSONTyped,
    HistogramBoundsToJSON,
    HistogramBoundsToJSONTyped,
} from './HistogramBounds';
import type { HistogramBuckets } from './HistogramBuckets';
import {
    HistogramBucketsFromJSON,
    HistogramBucketsFromJSONTyped,
    HistogramBucketsToJSON,
    HistogramBucketsToJSONTyped,
} from './HistogramBuckets';

/**
 * The parameter spec for `Histogram`
 * @export
 * @interface HistogramParameters
 */
export interface HistogramParameters {
    /**
     * If `data`, it computes the bounds of the underlying data.
     * If `{ "min": ..., "max": ... }`, one can specify custom bounds.
     * @type {HistogramBounds}
     * @memberof HistogramParameters
     */
    bounds: HistogramBounds;
    /**
     * The number of buckets. The value can be specified or calculated.
     * @type {HistogramBuckets}
     * @memberof HistogramParameters
     */
    buckets: HistogramBuckets;
    /**
     * Name of the (numeric) vector attribute or raster band to compute the histogram on.
     * @type {string}
     * @memberof HistogramParameters
     */
    columnName: string;
    /**
     * Flag, if the histogram should have user interactions for a range selection. It is `false` by default.
     * @type {boolean}
     * @memberof HistogramParameters
     */
    interactive?: boolean;
}

/**
 * Check if a given object implements the HistogramParameters interface.
 */
export function instanceOfHistogramParameters(value: object): value is HistogramParameters {
    if (!('bounds' in value) || value['bounds'] === undefined) return false;
    if (!('buckets' in value) || value['buckets'] === undefined) return false;
    if (!('columnName' in value) || value['columnName'] === undefined) return false;
    return true;
}

export function HistogramParametersFromJSON(json: any): HistogramParameters {
    return HistogramParametersFromJSONTyped(json, false);
}

export function HistogramParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistogramParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'bounds': HistogramBoundsFromJSON(json['bounds']),
        'buckets': HistogramBucketsFromJSON(json['buckets']),
        'columnName': json['columnName'],
        'interactive': json['interactive'] == null ? undefined : json['interactive'],
    };
}

export function HistogramParametersToJSON(json: any): HistogramParameters {
    return HistogramParametersToJSONTyped(json, false);
}

export function HistogramParametersToJSONTyped(value?: HistogramParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bounds': HistogramBoundsToJSON(value['bounds']),
        'buckets': HistogramBucketsToJSON(value['buckets']),
        'columnName': value['columnName'],
        'interactive': value['interactive'],
    };
}

