/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * The Landing page is the entry point of a OGC API.
 * 
 * The Landing page provides links to:
 * * the API definition (link relations `service-desc` and `service-doc`),
 * * the Conformance declaration (path `/conformance`, link relation `conformance`), and
 * * the Collections (path `/collections`, link relation `data`).
 * @export
 * @interface LandingPage
 */
export interface LandingPage {
    [key: string]: any | any;
    /**
     * The title of the API.
     * @type {string}
     * @memberof LandingPage
     */
    title?: string | null;
    /**
     * A textual description of the API.
     * @type {string}
     * @memberof LandingPage
     */
    description?: string | null;
    /**
     * Attribution for the API.
     * @type {string}
     * @memberof LandingPage
     */
    attribution?: string | null;
    /**
     * Links to the resources exposed through this API
     * @type {Array<Link>}
     * @memberof LandingPage
     */
    links?: Array<Link>;
}

/**
 * Check if a given object implements the LandingPage interface.
 */
export function instanceOfLandingPage(value: object): value is LandingPage {
    return true;
}

export function LandingPageFromJSON(json: any): LandingPage {
    return LandingPageFromJSONTyped(json, false);
}

export function LandingPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LandingPage {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'attribution': json['attribution'] == null ? undefined : json['attribution'],
        'links': json['links'] == null ? undefined : ((json['links'] as Array<any>).map(LinkFromJSON)),
    };
}

export function LandingPageToJSON(json: any): LandingPage {
    return LandingPageToJSONTyped(json, false);
}

export function LandingPageToJSONTyped(value?: LandingPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'title': value['title'],
        'description': value['description'],
        'attribution': value['attribution'],
        'links': value['links'] == null ? undefined : ((value['links'] as Array<any>).map(LinkToJSON)),
    };
}

