/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LayerResource
 */
export interface LayerResource {
    /**
     * 
     * @type {string}
     * @memberof LayerResource
     */
    id: string;
    /**
     * 
     * @type {LayerResourceTypeEnum}
     * @memberof LayerResource
     */
    type: LayerResourceTypeEnum;
}


/**
 * @export
 */
export const LayerResourceTypeEnum = {
    Layer: 'layer'
} as const;
export type LayerResourceTypeEnum = typeof LayerResourceTypeEnum[keyof typeof LayerResourceTypeEnum];


/**
 * Check if a given object implements the LayerResource interface.
 */
export function instanceOfLayerResource(value: object): value is LayerResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function LayerResourceFromJSON(json: any): LayerResource {
    return LayerResourceFromJSONTyped(json, false);
}

export function LayerResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayerResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function LayerResourceToJSON(json: any): LayerResource {
    return LayerResourceToJSONTyped(json, false);
}

export function LayerResourceToJSONTyped(value?: LayerResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

