/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LayerVisibility
 */
export interface LayerVisibility {
    /**
     * 
     * @type {boolean}
     * @memberof LayerVisibility
     */
    data: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LayerVisibility
     */
    legend: boolean;
}

/**
 * Check if a given object implements the LayerVisibility interface.
 */
export function instanceOfLayerVisibility(value: object): value is LayerVisibility {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('legend' in value) || value['legend'] === undefined) return false;
    return true;
}

export function LayerVisibilityFromJSON(json: any): LayerVisibility {
    return LayerVisibilityFromJSONTyped(json, false);
}

export function LayerVisibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayerVisibility {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'legend': json['legend'],
    };
}

export function LayerVisibilityToJSON(json: any): LayerVisibility {
    return LayerVisibilityToJSONTyped(json, false);
}

export function LayerVisibilityToJSONTyped(value?: LayerVisibility | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'legend': value['legend'],
    };
}

