/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LayerProviderListing
 */
export interface LayerProviderListing {
    /**
     * 
     * @type {string}
     * @memberof LayerProviderListing
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LayerProviderListing
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof LayerProviderListing
     */
    priority: number;
}

/**
 * Check if a given object implements the LayerProviderListing interface.
 */
export function instanceOfLayerProviderListing(value: object): value is LayerProviderListing {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    return true;
}

export function LayerProviderListingFromJSON(json: any): LayerProviderListing {
    return LayerProviderListingFromJSONTyped(json, false);
}

export function LayerProviderListingFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayerProviderListing {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'priority': json['priority'],
    };
}

export function LayerProviderListingToJSON(json: any): LayerProviderListing {
    return LayerProviderListingToJSONTyped(json, false);
}

export function LayerProviderListingToJSONTyped(value?: LayerProviderListing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'priority': value['priority'],
    };
}

