/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Coordinate2D } from './Coordinate2D';
import {
    Coordinate2DFromJSON,
    Coordinate2DFromJSONTyped,
    Coordinate2DToJSON,
    Coordinate2DToJSONTyped,
} from './Coordinate2D';

/**
 * 
 * @export
 * @interface MockDatasetDataSourceLoadingInfo
 */
export interface MockDatasetDataSourceLoadingInfo {
    /**
     * 
     * @type {Array<Coordinate2D>}
     * @memberof MockDatasetDataSourceLoadingInfo
     */
    points: Array<Coordinate2D>;
}

/**
 * Check if a given object implements the MockDatasetDataSourceLoadingInfo interface.
 */
export function instanceOfMockDatasetDataSourceLoadingInfo(value: object): value is MockDatasetDataSourceLoadingInfo {
    if (!('points' in value) || value['points'] === undefined) return false;
    return true;
}

export function MockDatasetDataSourceLoadingInfoFromJSON(json: any): MockDatasetDataSourceLoadingInfo {
    return MockDatasetDataSourceLoadingInfoFromJSONTyped(json, false);
}

export function MockDatasetDataSourceLoadingInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockDatasetDataSourceLoadingInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'points': ((json['points'] as Array<any>).map(Coordinate2DFromJSON)),
    };
}

export function MockDatasetDataSourceLoadingInfoToJSON(json: any): MockDatasetDataSourceLoadingInfo {
    return MockDatasetDataSourceLoadingInfoToJSONTyped(json, false);
}

export function MockDatasetDataSourceLoadingInfoToJSONTyped(value?: MockDatasetDataSourceLoadingInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'points': ((value['points'] as Array<any>).map(Coordinate2DToJSON)),
    };
}

