/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultipleRasterOrSingleVectorOperator } from './MultipleRasterOrSingleVectorOperator';
import {
    MultipleRasterOrSingleVectorOperatorFromJSON,
    MultipleRasterOrSingleVectorOperatorFromJSONTyped,
    MultipleRasterOrSingleVectorOperatorToJSON,
    MultipleRasterOrSingleVectorOperatorToJSONTyped,
} from './MultipleRasterOrSingleVectorOperator';

/**
 * Either one or more raster operators or a single vector operator as source for this operator.
 * @export
 * @interface MultipleRasterOrSingleVectorSource
 */
export interface MultipleRasterOrSingleVectorSource {
    /**
     * 
     * @type {MultipleRasterOrSingleVectorOperator}
     * @memberof MultipleRasterOrSingleVectorSource
     */
    source: MultipleRasterOrSingleVectorOperator;
}

/**
 * Check if a given object implements the MultipleRasterOrSingleVectorSource interface.
 */
export function instanceOfMultipleRasterOrSingleVectorSource(value: object): value is MultipleRasterOrSingleVectorSource {
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function MultipleRasterOrSingleVectorSourceFromJSON(json: any): MultipleRasterOrSingleVectorSource {
    return MultipleRasterOrSingleVectorSourceFromJSONTyped(json, false);
}

export function MultipleRasterOrSingleVectorSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultipleRasterOrSingleVectorSource {
    if (json == null) {
        return json;
    }
    return {
        
        'source': MultipleRasterOrSingleVectorOperatorFromJSON(json['source']),
    };
}

export function MultipleRasterOrSingleVectorSourceToJSON(json: any): MultipleRasterOrSingleVectorSource {
    return MultipleRasterOrSingleVectorSourceToJSONTyped(json, false);
}

export function MultipleRasterOrSingleVectorSourceToJSONTyped(value?: MultipleRasterOrSingleVectorSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': MultipleRasterOrSingleVectorOperatorToJSON(value['source']),
    };
}

