/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FormatSpecifics } from './FormatSpecifics';
import {
    FormatSpecificsFromJSON,
    FormatSpecificsFromJSONTyped,
    FormatSpecificsToJSON,
    FormatSpecificsToJSONTyped,
} from './FormatSpecifics';

/**
 * 
 * @export
 * @interface OgrSourceColumnSpec
 */
export interface OgrSourceColumnSpec {
    /**
     * 
     * @type {FormatSpecifics}
     * @memberof OgrSourceColumnSpec
     */
    formatSpecifics?: FormatSpecifics | null;
    /**
     * 
     * @type {string}
     * @memberof OgrSourceColumnSpec
     */
    x: string;
    /**
     * 
     * @type {string}
     * @memberof OgrSourceColumnSpec
     */
    y?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof OgrSourceColumnSpec
     */
    _int?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OgrSourceColumnSpec
     */
    _float?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OgrSourceColumnSpec
     */
    text?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OgrSourceColumnSpec
     */
    bool?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OgrSourceColumnSpec
     */
    datetime?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof OgrSourceColumnSpec
     */
    rename?: { [key: string]: string; };
}

/**
 * Check if a given object implements the OgrSourceColumnSpec interface.
 */
export function instanceOfOgrSourceColumnSpec(value: object): value is OgrSourceColumnSpec {
    if (!('x' in value) || value['x'] === undefined) return false;
    return true;
}

export function OgrSourceColumnSpecFromJSON(json: any): OgrSourceColumnSpec {
    return OgrSourceColumnSpecFromJSONTyped(json, false);
}

export function OgrSourceColumnSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): OgrSourceColumnSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'formatSpecifics': json['formatSpecifics'] == null ? undefined : FormatSpecificsFromJSON(json['formatSpecifics']),
        'x': json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        '_int': json['int'] == null ? undefined : json['int'],
        '_float': json['float'] == null ? undefined : json['float'],
        'text': json['text'] == null ? undefined : json['text'],
        'bool': json['bool'] == null ? undefined : json['bool'],
        'datetime': json['datetime'] == null ? undefined : json['datetime'],
        'rename': json['rename'] == null ? undefined : json['rename'],
    };
}

export function OgrSourceColumnSpecToJSON(json: any): OgrSourceColumnSpec {
    return OgrSourceColumnSpecToJSONTyped(json, false);
}

export function OgrSourceColumnSpecToJSONTyped(value?: OgrSourceColumnSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'formatSpecifics': FormatSpecificsToJSON(value['formatSpecifics']),
        'x': value['x'],
        'y': value['y'],
        'int': value['_int'],
        'float': value['_float'],
        'text': value['text'],
        'bool': value['bool'],
        'datetime': value['datetime'],
        'rename': value['rename'],
    };
}

