/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PieChartCountType
 */
export interface PieChartCountType {
    /**
     * 
     * @type {PieChartCountTypeTypeEnum}
     * @memberof PieChartCountType
     */
    type: PieChartCountTypeTypeEnum;
    /**
     * The names of the attribute to generate pies for.
     * @type {string}
     * @memberof PieChartCountType
     */
    columnName: string;
    /**
     * Whether to render the chart as a donut.
     * @type {boolean}
     * @memberof PieChartCountType
     */
    donut?: boolean;
}


/**
 * @export
 */
export const PieChartCountTypeTypeEnum = {
    Count: 'count'
} as const;
export type PieChartCountTypeTypeEnum = typeof PieChartCountTypeTypeEnum[keyof typeof PieChartCountTypeTypeEnum];


/**
 * Check if a given object implements the PieChartCountType interface.
 */
export function instanceOfPieChartCountType(value: object): value is PieChartCountType {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('columnName' in value) || value['columnName'] === undefined) return false;
    return true;
}

export function PieChartCountTypeFromJSON(json: any): PieChartCountType {
    return PieChartCountTypeFromJSONTyped(json, false);
}

export function PieChartCountTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PieChartCountType {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'columnName': json['columnName'],
        'donut': json['donut'] == null ? undefined : json['donut'],
    };
}

export function PieChartCountTypeToJSON(json: any): PieChartCountType {
    return PieChartCountTypeToJSONTyped(json, false);
}

export function PieChartCountTypeToJSONTyped(value?: PieChartCountType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'columnName': value['columnName'],
        'donut': value['donut'],
    };
}

