/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Plot
 */
export interface Plot {
    /**
     * 
     * @type {string}
     * @memberof Plot
     */
    workflow: string;
    /**
     * 
     * @type {string}
     * @memberof Plot
     */
    name: string;
}

/**
 * Check if a given object implements the Plot interface.
 */
export function instanceOfPlot(value: object): value is Plot {
    if (!('workflow' in value) || value['workflow'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PlotFromJSON(json: any): Plot {
    return PlotFromJSONTyped(json, false);
}

export function PlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plot {
    if (json == null) {
        return json;
    }
    return {
        
        'workflow': json['workflow'],
        'name': json['name'],
    };
}

export function PlotToJSON(json: any): Plot {
    return PlotToJSONTyped(json, false);
}

export function PlotToJSONTyped(value?: Plot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflow': value['workflow'],
        'name': value['name'],
    };
}

