/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Provenance } from './Provenance';
import {
    ProvenanceFromJSON,
    ProvenanceFromJSONTyped,
    ProvenanceToJSON,
    ProvenanceToJSONTyped,
} from './Provenance';

/**
 * 
 * @export
 * @interface Provenances
 */
export interface Provenances {
    /**
     * 
     * @type {Array<Provenance>}
     * @memberof Provenances
     */
    provenances: Array<Provenance>;
}

/**
 * Check if a given object implements the Provenances interface.
 */
export function instanceOfProvenances(value: object): value is Provenances {
    if (!('provenances' in value) || value['provenances'] === undefined) return false;
    return true;
}

export function ProvenancesFromJSON(json: any): Provenances {
    return ProvenancesFromJSONTyped(json, false);
}

export function ProvenancesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Provenances {
    if (json == null) {
        return json;
    }
    return {
        
        'provenances': ((json['provenances'] as Array<any>).map(ProvenanceFromJSON)),
    };
}

export function ProvenancesToJSON(json: any): Provenances {
    return ProvenancesToJSONTyped(json, false);
}

export function ProvenancesToJSONTyped(value?: Provenances | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provenances': ((value['provenances'] as Array<any>).map(ProvenanceToJSON)),
    };
}

