/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeInterval } from './TimeInterval';
import {
    TimeIntervalFromJSON,
    TimeIntervalFromJSONTyped,
    TimeIntervalToJSON,
    TimeIntervalToJSONTyped,
} from './TimeInterval';
import type { SpatialPartition2D } from './SpatialPartition2D';
import {
    SpatialPartition2DFromJSON,
    SpatialPartition2DFromJSONTyped,
    SpatialPartition2DToJSON,
    SpatialPartition2DToJSONTyped,
} from './SpatialPartition2D';

/**
 * A spatio-temporal rectangle with a specified resolution
 * @export
 * @interface RasterToDatasetQueryRectangle
 */
export interface RasterToDatasetQueryRectangle {
    /**
     * 
     * @type {SpatialPartition2D}
     * @memberof RasterToDatasetQueryRectangle
     */
    spatialBounds: SpatialPartition2D;
    /**
     * 
     * @type {TimeInterval}
     * @memberof RasterToDatasetQueryRectangle
     */
    timeInterval: TimeInterval;
}

/**
 * Check if a given object implements the RasterToDatasetQueryRectangle interface.
 */
export function instanceOfRasterToDatasetQueryRectangle(value: object): value is RasterToDatasetQueryRectangle {
    if (!('spatialBounds' in value) || value['spatialBounds'] === undefined) return false;
    if (!('timeInterval' in value) || value['timeInterval'] === undefined) return false;
    return true;
}

export function RasterToDatasetQueryRectangleFromJSON(json: any): RasterToDatasetQueryRectangle {
    return RasterToDatasetQueryRectangleFromJSONTyped(json, false);
}

export function RasterToDatasetQueryRectangleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RasterToDatasetQueryRectangle {
    if (json == null) {
        return json;
    }
    return {
        
        'spatialBounds': SpatialPartition2DFromJSON(json['spatialBounds']),
        'timeInterval': TimeIntervalFromJSON(json['timeInterval']),
    };
}

export function RasterToDatasetQueryRectangleToJSON(json: any): RasterToDatasetQueryRectangle {
    return RasterToDatasetQueryRectangleToJSONTyped(json, false);
}

export function RasterToDatasetQueryRectangleToJSONTyped(value?: RasterToDatasetQueryRectangle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spatialBounds': SpatialPartition2DToJSON(value['spatialBounds']),
        'timeInterval': TimeIntervalToJSON(value['timeInterval']),
    };
}

