/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Default } from './Default';
import {
    instanceOfDefault,
    DefaultFromJSON,
    DefaultFromJSONTyped,
    DefaultToJSON,
} from './Default';
import type { Rename } from './Rename';
import {
    instanceOfRename,
    RenameFromJSON,
    RenameFromJSONTyped,
    RenameToJSON,
} from './Rename';
import type { Suffix } from './Suffix';
import {
    instanceOfSuffix,
    SuffixFromJSON,
    SuffixFromJSONTyped,
    SuffixToJSON,
} from './Suffix';

/**
 * @type RenameBands
 * 
 * @export
 */
export type RenameBands = Default | Rename | Suffix;

export function RenameBandsFromJSON(json: any): RenameBands {
    return RenameBandsFromJSONTyped(json, false);
}

export function RenameBandsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameBands {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDefault(json)) {
        return DefaultFromJSONTyped(json, true);
    }
    if (instanceOfRename(json)) {
        return RenameFromJSONTyped(json, true);
    }
    if (instanceOfSuffix(json)) {
        return SuffixFromJSONTyped(json, true);
    }
    return {} as any;
}

export function RenameBandsToJSON(json: any): any {
    return RenameBandsToJSONTyped(json, false);
}

export function RenameBandsToJSONTyped(value?: RenameBands | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDefault(value)) {
        return DefaultToJSON(value as Default);
    }
    if (instanceOfRename(value)) {
        return RenameToJSON(value as Rename);
    }
    if (instanceOfSuffix(value)) {
        return SuffixToJSON(value as Suffix);
    }
    return {};
}

