/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Append ` (n)` to the band name for the `n`-th conflict.
 * @export
 * @interface RenameBandsDefault
 */
export interface RenameBandsDefault {
    /**
     * 
     * @type {RenameBandsDefaultTypeEnum}
     * @memberof RenameBandsDefault
     */
    type: RenameBandsDefaultTypeEnum;
}


/**
 * @export
 */
export const RenameBandsDefaultTypeEnum = {
    Default: 'default'
} as const;
export type RenameBandsDefaultTypeEnum = typeof RenameBandsDefaultTypeEnum[keyof typeof RenameBandsDefaultTypeEnum];


/**
 * Check if a given object implements the RenameBandsDefault interface.
 */
export function instanceOfRenameBandsDefault(value: object): value is RenameBandsDefault {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RenameBandsDefaultFromJSON(json: any): RenameBandsDefault {
    return RenameBandsDefaultFromJSONTyped(json, false);
}

export function RenameBandsDefaultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameBandsDefault {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function RenameBandsDefaultToJSON(json: any): RenameBandsDefault {
    return RenameBandsDefaultToJSONTyped(json, false);
}

export function RenameBandsDefaultToJSONTyped(value?: RenameBandsDefault | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

