/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ScalingModeMulSlopeAddOffset } from './ScalingModeMulSlopeAddOffset';
import {
    instanceOfScalingModeMulSlopeAddOffset,
    ScalingModeMulSlopeAddOffsetFromJSON,
    ScalingModeMulSlopeAddOffsetFromJSONTyped,
    ScalingModeMulSlopeAddOffsetToJSON,
} from './ScalingModeMulSlopeAddOffset';
import type { ScalingModeSubOffsetDivSlope } from './ScalingModeSubOffsetDivSlope';
import {
    instanceOfScalingModeSubOffsetDivSlope,
    ScalingModeSubOffsetDivSlopeFromJSON,
    ScalingModeSubOffsetDivSlopeFromJSONTyped,
    ScalingModeSubOffsetDivSlopeToJSON,
} from './ScalingModeSubOffsetDivSlope';

/**
 * @type ScalingMode
 * 
 * @export
 */
export type ScalingMode = { type: 'mulSlopeAddOffset' } & ScalingModeMulSlopeAddOffset | { type: 'subOffsetDivSlope' } & ScalingModeSubOffsetDivSlope;

export function ScalingModeFromJSON(json: any): ScalingMode {
    return ScalingModeFromJSONTyped(json, false);
}

export function ScalingModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScalingMode {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'mulSlopeAddOffset':
            return Object.assign({}, ScalingModeMulSlopeAddOffsetFromJSONTyped(json, true), { type: 'mulSlopeAddOffset' } as const);
        case 'subOffsetDivSlope':
            return Object.assign({}, ScalingModeSubOffsetDivSlopeFromJSONTyped(json, true), { type: 'subOffsetDivSlope' } as const);
        default:
            return json;
    }
}

export function ScalingModeToJSON(json: any): any {
    return ScalingModeToJSONTyped(json, false);
}

export function ScalingModeToJSONTyped(value?: ScalingMode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'mulSlopeAddOffset':
            return Object.assign({}, ScalingModeMulSlopeAddOffsetToJSON(value), { type: 'mulSlopeAddOffset' } as const);
        case 'subOffsetDivSlope':
            return Object.assign({}, ScalingModeSubOffsetDivSlopeToJSON(value), { type: 'subOffsetDivSlope' } as const);
        default:
            return value;
    }
}

