/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StacApiRetries } from './StacApiRetries';
import {
    StacApiRetriesFromJSON,
    StacApiRetriesFromJSONTyped,
    StacApiRetriesToJSON,
    StacApiRetriesToJSONTyped,
} from './StacApiRetries';
import type { StacQueryBuffer } from './StacQueryBuffer';
import {
    StacQueryBufferFromJSON,
    StacQueryBufferFromJSONTyped,
    StacQueryBufferToJSON,
    StacQueryBufferToJSONTyped,
} from './StacQueryBuffer';

/**
 * 
 * @export
 * @interface SentinelS2L2ACogsProviderDefinition
 */
export interface SentinelS2L2ACogsProviderDefinition {
    /**
     * 
     * @type {SentinelS2L2ACogsProviderDefinitionTypeEnum}
     * @memberof SentinelS2L2ACogsProviderDefinition
     */
    type: SentinelS2L2ACogsProviderDefinitionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SentinelS2L2ACogsProviderDefinition
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SentinelS2L2ACogsProviderDefinition
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SentinelS2L2ACogsProviderDefinition
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof SentinelS2L2ACogsProviderDefinition
     */
    priority?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SentinelS2L2ACogsProviderDefinition
     */
    apiUrl: string;
    /**
     * 
     * @type {StacApiRetries}
     * @memberof SentinelS2L2ACogsProviderDefinition
     */
    stacApiRetries?: StacApiRetries;
    /**
     * 
     * @type {number}
     * @memberof SentinelS2L2ACogsProviderDefinition
     */
    gdalRetries?: number;
    /**
     * 
     * @type {number}
     * @memberof SentinelS2L2ACogsProviderDefinition
     */
    cacheTtl?: number;
    /**
     * 
     * @type {StacQueryBuffer}
     * @memberof SentinelS2L2ACogsProviderDefinition
     */
    queryBuffer?: StacQueryBuffer;
}


/**
 * @export
 */
export const SentinelS2L2ACogsProviderDefinitionTypeEnum = {
    SentinelS2L2ACogs: 'SentinelS2L2ACogs'
} as const;
export type SentinelS2L2ACogsProviderDefinitionTypeEnum = typeof SentinelS2L2ACogsProviderDefinitionTypeEnum[keyof typeof SentinelS2L2ACogsProviderDefinitionTypeEnum];


/**
 * Check if a given object implements the SentinelS2L2ACogsProviderDefinition interface.
 */
export function instanceOfSentinelS2L2ACogsProviderDefinition(value: object): value is SentinelS2L2ACogsProviderDefinition {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('apiUrl' in value) || value['apiUrl'] === undefined) return false;
    return true;
}

export function SentinelS2L2ACogsProviderDefinitionFromJSON(json: any): SentinelS2L2ACogsProviderDefinition {
    return SentinelS2L2ACogsProviderDefinitionFromJSONTyped(json, false);
}

export function SentinelS2L2ACogsProviderDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SentinelS2L2ACogsProviderDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'id': json['id'],
        'description': json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'apiUrl': json['apiUrl'],
        'stacApiRetries': json['stacApiRetries'] == null ? undefined : StacApiRetriesFromJSON(json['stacApiRetries']),
        'gdalRetries': json['gdalRetries'] == null ? undefined : json['gdalRetries'],
        'cacheTtl': json['cacheTtl'] == null ? undefined : json['cacheTtl'],
        'queryBuffer': json['queryBuffer'] == null ? undefined : StacQueryBufferFromJSON(json['queryBuffer']),
    };
}

export function SentinelS2L2ACogsProviderDefinitionToJSON(json: any): SentinelS2L2ACogsProviderDefinition {
    return SentinelS2L2ACogsProviderDefinitionToJSONTyped(json, false);
}

export function SentinelS2L2ACogsProviderDefinitionToJSONTyped(value?: SentinelS2L2ACogsProviderDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'id': value['id'],
        'description': value['description'],
        'priority': value['priority'],
        'apiUrl': value['apiUrl'],
        'stacApiRetries': StacApiRetriesToJSON(value['stacApiRetries']),
        'gdalRetries': value['gdalRetries'],
        'cacheTtl': value['cacheTtl'],
        'queryBuffer': StacQueryBufferToJSON(value['queryBuffer']),
    };
}

