/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpatialBoundsDeriveNone
 */
export interface SpatialBoundsDeriveNone {
    /**
     * 
     * @type {SpatialBoundsDeriveNoneTypeEnum}
     * @memberof SpatialBoundsDeriveNone
     */
    type: SpatialBoundsDeriveNoneTypeEnum;
}


/**
 * @export
 */
export const SpatialBoundsDeriveNoneTypeEnum = {
    None: 'none'
} as const;
export type SpatialBoundsDeriveNoneTypeEnum = typeof SpatialBoundsDeriveNoneTypeEnum[keyof typeof SpatialBoundsDeriveNoneTypeEnum];


/**
 * Check if a given object implements the SpatialBoundsDeriveNone interface.
 */
export function instanceOfSpatialBoundsDeriveNone(value: object): value is SpatialBoundsDeriveNone {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SpatialBoundsDeriveNoneFromJSON(json: any): SpatialBoundsDeriveNone {
    return SpatialBoundsDeriveNoneFromJSONTyped(json, false);
}

export function SpatialBoundsDeriveNoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpatialBoundsDeriveNone {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function SpatialBoundsDeriveNoneToJSON(json: any): SpatialBoundsDeriveNone {
    return SpatialBoundsDeriveNoneToJSONTyped(json, false);
}

export function SpatialBoundsDeriveNoneToJSONTyped(value?: SpatialBoundsDeriveNone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

