/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpatialResolution } from './SpatialResolution';
import {
    SpatialResolutionFromJSON,
    SpatialResolutionFromJSONTyped,
    SpatialResolutionToJSON,
    SpatialResolutionToJSONTyped,
} from './SpatialResolution';
import type { StacProviderDatasetBand } from './StacProviderDatasetBand';
import {
    StacProviderDatasetBandFromJSON,
    StacProviderDatasetBandFromJSONTyped,
    StacProviderDatasetBandToJSON,
    StacProviderDatasetBandToJSONTyped,
} from './StacProviderDatasetBand';
import type { SpatialGridDescriptor } from './SpatialGridDescriptor';
import {
    SpatialGridDescriptorFromJSON,
    SpatialGridDescriptorFromJSONTyped,
    SpatialGridDescriptorToJSON,
    SpatialGridDescriptorToJSONTyped,
} from './SpatialGridDescriptor';
import type { RasterDataType } from './RasterDataType';
import {
    RasterDataTypeFromJSON,
    RasterDataTypeFromJSONTyped,
    RasterDataTypeToJSON,
    RasterDataTypeToJSONTyped,
} from './RasterDataType';

/**
 * 
 * @export
 * @interface StacProviderDataset
 */
export interface StacProviderDataset {
    /**
     * 
     * @type {string}
     * @memberof StacProviderDataset
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StacProviderDataset
     */
    description: string;
    /**
     * 
     * @type {RasterDataType}
     * @memberof StacProviderDataset
     */
    dataType: RasterDataType;
    /**
     * 
     * @type {SpatialResolution}
     * @memberof StacProviderDataset
     */
    resolution: SpatialResolution;
    /**
     * 
     * @type {string}
     * @memberof StacProviderDataset
     */
    projection: string;
    /**
     * 
     * @type {SpatialGridDescriptor}
     * @memberof StacProviderDataset
     */
    spatialGrid: SpatialGridDescriptor;
    /**
     * 
     * @type {Array<StacProviderDatasetBand>}
     * @memberof StacProviderDataset
     */
    bands: Array<StacProviderDatasetBand>;
}



/**
 * Check if a given object implements the StacProviderDataset interface.
 */
export function instanceOfStacProviderDataset(value: object): value is StacProviderDataset {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    if (!('resolution' in value) || value['resolution'] === undefined) return false;
    if (!('projection' in value) || value['projection'] === undefined) return false;
    if (!('spatialGrid' in value) || value['spatialGrid'] === undefined) return false;
    if (!('bands' in value) || value['bands'] === undefined) return false;
    return true;
}

export function StacProviderDatasetFromJSON(json: any): StacProviderDataset {
    return StacProviderDatasetFromJSONTyped(json, false);
}

export function StacProviderDatasetFromJSONTyped(json: any, ignoreDiscriminator: boolean): StacProviderDataset {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'dataType': RasterDataTypeFromJSON(json['dataType']),
        'resolution': SpatialResolutionFromJSON(json['resolution']),
        'projection': json['projection'],
        'spatialGrid': SpatialGridDescriptorFromJSON(json['spatialGrid']),
        'bands': ((json['bands'] as Array<any>).map(StacProviderDatasetBandFromJSON)),
    };
}

export function StacProviderDatasetToJSON(json: any): StacProviderDataset {
    return StacProviderDatasetToJSONTyped(json, false);
}

export function StacProviderDatasetToJSONTyped(value?: StacProviderDataset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'dataType': RasterDataTypeToJSON(value['dataType']),
        'resolution': SpatialResolutionToJSON(value['resolution']),
        'projection': value['projection'],
        'spatialGrid': SpatialGridDescriptorToJSON(value['spatialGrid']),
        'bands': ((value['bands'] as Array<any>).map(StacProviderDatasetBandToJSON)),
    };
}

