/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A struct that represents buffers to apply to stac requests
 * @export
 * @interface StacQueryBuffer
 */
export interface StacQueryBuffer {
    /**
     * 
     * @type {number}
     * @memberof StacQueryBuffer
     */
    endSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof StacQueryBuffer
     */
    startSeconds: number;
}

/**
 * Check if a given object implements the StacQueryBuffer interface.
 */
export function instanceOfStacQueryBuffer(value: object): value is StacQueryBuffer {
    if (!('endSeconds' in value) || value['endSeconds'] === undefined) return false;
    if (!('startSeconds' in value) || value['startSeconds'] === undefined) return false;
    return true;
}

export function StacQueryBufferFromJSON(json: any): StacQueryBuffer {
    return StacQueryBufferFromJSONTyped(json, false);
}

export function StacQueryBufferFromJSONTyped(json: any, ignoreDiscriminator: boolean): StacQueryBuffer {
    if (json == null) {
        return json;
    }
    return {
        
        'endSeconds': json['endSeconds'],
        'startSeconds': json['startSeconds'],
    };
}

export function StacQueryBufferToJSON(json: any): StacQueryBuffer {
    return StacQueryBufferToJSONTyped(json, false);
}

export function StacQueryBufferToJSONTyped(value?: StacQueryBuffer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endSeconds': value['endSeconds'],
        'startSeconds': value['startSeconds'],
    };
}

