/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Aggregation } from './Aggregation';
import {
    AggregationFromJSON,
    AggregationFromJSONTyped,
    AggregationToJSON,
    AggregationToJSONTyped,
} from './Aggregation';
import type { TimeStep } from './TimeStep';
import {
    TimeStepFromJSON,
    TimeStepFromJSONTyped,
    TimeStepToJSON,
    TimeStepToJSONTyped,
} from './TimeStep';
import type { RasterDataType } from './RasterDataType';
import {
    RasterDataTypeFromJSON,
    RasterDataTypeFromJSONTyped,
    RasterDataTypeToJSON,
    RasterDataTypeToJSONTyped,
} from './RasterDataType';

/**
 * Parameters for the `TemporalRasterAggregation` operator.
 * @export
 * @interface TemporalRasterAggregationParameters
 */
export interface TemporalRasterAggregationParameters {
    /**
     * Aggregation method for values within each time window.
     * 
     * Encountering NO DATA makes the aggregation result NO DATA unless
     * `ignoreNoData` is `true` for the selected aggregation variant.
     * @type {Aggregation}
     * @memberof TemporalRasterAggregationParameters
     */
    aggregation: Aggregation;
    /**
     * Optional output raster data type.
     * @type {RasterDataType}
     * @memberof TemporalRasterAggregationParameters
     */
    outputType?: RasterDataType | null;
    /**
     * Window size and granularity for the output time series.
     * @type {TimeStep}
     * @memberof TemporalRasterAggregationParameters
     */
    window: TimeStep;
    /**
     * Optional reference timestamp used as the anchor for window boundaries.
     * 
     * If omitted, windows are anchored at `1970-01-01T00:00:00Z`.
     * @type {number}
     * @memberof TemporalRasterAggregationParameters
     */
    windowReference?: number | null;
}



/**
 * Check if a given object implements the TemporalRasterAggregationParameters interface.
 */
export function instanceOfTemporalRasterAggregationParameters(value: object): value is TemporalRasterAggregationParameters {
    if (!('aggregation' in value) || value['aggregation'] === undefined) return false;
    if (!('window' in value) || value['window'] === undefined) return false;
    return true;
}

export function TemporalRasterAggregationParametersFromJSON(json: any): TemporalRasterAggregationParameters {
    return TemporalRasterAggregationParametersFromJSONTyped(json, false);
}

export function TemporalRasterAggregationParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemporalRasterAggregationParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'aggregation': AggregationFromJSON(json['aggregation']),
        'outputType': json['outputType'] == null ? undefined : RasterDataTypeFromJSON(json['outputType']),
        'window': TimeStepFromJSON(json['window']),
        'windowReference': json['windowReference'] == null ? undefined : json['windowReference'],
    };
}

export function TemporalRasterAggregationParametersToJSON(json: any): TemporalRasterAggregationParameters {
    return TemporalRasterAggregationParametersToJSONTyped(json, false);
}

export function TemporalRasterAggregationParametersToJSONTyped(value?: TemporalRasterAggregationParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aggregation': AggregationToJSON(value['aggregation']),
        'outputType': RasterDataTypeToJSON(value['outputType']),
        'window': TimeStepToJSON(value['window']),
        'windowReference': value['windowReference'],
    };
}

