/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TileMatrixSetIdOneOf
 */
export interface TileMatrixSetIdOneOf {
    /**
     * 
     * @type {string}
     * @memberof TileMatrixSetIdOneOf
     */
    custom: string;
}

/**
 * Check if a given object implements the TileMatrixSetIdOneOf interface.
 */
export function instanceOfTileMatrixSetIdOneOf(value: object): value is TileMatrixSetIdOneOf {
    if (!('custom' in value) || value['custom'] === undefined) return false;
    return true;
}

export function TileMatrixSetIdOneOfFromJSON(json: any): TileMatrixSetIdOneOf {
    return TileMatrixSetIdOneOfFromJSONTyped(json, false);
}

export function TileMatrixSetIdOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TileMatrixSetIdOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'custom': json['Custom'],
    };
}

export function TileMatrixSetIdOneOfToJSON(json: any): TileMatrixSetIdOneOf {
    return TileMatrixSetIdOneOfToJSONTyped(json, false);
}

export function TileMatrixSetIdOneOfToJSONTyped(value?: TileMatrixSetIdOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Custom': value['custom'],
    };
}

