/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TileSetItem } from './TileSetItem';
import {
    TileSetItemFromJSON,
    TileSetItemFromJSONTyped,
    TileSetItemToJSON,
    TileSetItemToJSONTyped,
} from './TileSetItem';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface TileSets
 */
export interface TileSets {
    /**
     * 
     * @type {Array<TileSetItem>}
     * @memberof TileSets
     */
    tilesets: Array<TileSetItem>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof TileSets
     */
    links?: Array<Link>;
}

/**
 * Check if a given object implements the TileSets interface.
 */
export function instanceOfTileSets(value: object): value is TileSets {
    if (!('tilesets' in value) || value['tilesets'] === undefined) return false;
    return true;
}

export function TileSetsFromJSON(json: any): TileSets {
    return TileSetsFromJSONTyped(json, false);
}

export function TileSetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TileSets {
    if (json == null) {
        return json;
    }
    return {
        
        'tilesets': ((json['tilesets'] as Array<any>).map(TileSetItemFromJSON)),
        'links': json['links'] == null ? undefined : ((json['links'] as Array<any>).map(LinkFromJSON)),
    };
}

export function TileSetsToJSON(json: any): TileSets {
    return TileSetsToJSONTyped(json, false);
}

export function TileSetsToJSONTyped(value?: TileSets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tilesets': ((value['tilesets'] as Array<any>).map(TileSetItemToJSON)),
        'links': value['links'] == null ? undefined : ((value['links'] as Array<any>).map(LinkToJSON)),
    };
}

