/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypedGeometryNoGeometry
 */
export interface TypedGeometryNoGeometry {
    /**
     * 
     * @type {any}
     * @memberof TypedGeometryNoGeometry
     */
    data: any | null;
}

/**
 * Check if a given object implements the TypedGeometryNoGeometry interface.
 */
export function instanceOfTypedGeometryNoGeometry(value: object): value is TypedGeometryNoGeometry {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TypedGeometryNoGeometryFromJSON(json: any): TypedGeometryNoGeometry {
    return TypedGeometryNoGeometryFromJSONTyped(json, false);
}

export function TypedGeometryNoGeometryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedGeometryNoGeometry {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['Data'],
    };
}

export function TypedGeometryNoGeometryToJSON(json: any): TypedGeometryNoGeometry {
    return TypedGeometryNoGeometryToJSONTyped(json, false);
}

export function TypedGeometryNoGeometryToJSONTyped(value?: TypedGeometryNoGeometry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Data': value['data'],
    };
}

