/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WmsService = {
    Wms: 'WMS'
} as const;
export type WmsService = typeof WmsService[keyof typeof WmsService];


export function instanceOfWmsService(value: any): boolean {
    for (const key in WmsService) {
        if (Object.prototype.hasOwnProperty.call(WmsService, key)) {
            if (WmsService[key as keyof typeof WmsService] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WmsServiceFromJSON(json: any): WmsService {
    return WmsServiceFromJSONTyped(json, false);
}

export function WmsServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WmsService {
    return json as WmsService;
}

export function WmsServiceToJSON(value?: WmsService | null): any {
    return value as any;
}

export function WmsServiceToJSONTyped(value: any, ignoreDiscriminator: boolean): WmsService {
    return value as WmsService;
}

