# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from geoengine_api_client.models.count_aggregation import CountAggregation
from geoengine_api_client.models.first_aggregation import FirstAggregation
from geoengine_api_client.models.last_aggregation import LastAggregation
from geoengine_api_client.models.max_aggregation import MaxAggregation
from geoengine_api_client.models.mean_aggregation import MeanAggregation
from geoengine_api_client.models.min_aggregation import MinAggregation
from geoengine_api_client.models.percentile_estimate_aggregation import PercentileEstimateAggregation
from geoengine_api_client.models.sum_aggregation import SumAggregation
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

AGGREGATION_ONE_OF_SCHEMAS = ["CountAggregation", "FirstAggregation", "LastAggregation", "MaxAggregation", "MeanAggregation", "MinAggregation", "PercentileEstimateAggregation", "SumAggregation"]

class Aggregation(BaseModel):
    """
    Aggregation methods for `TemporalRasterAggregation`.  Available variants are `min`, `max`, `first`, `last`, `mean`, `sum`, `count`, and `percentileEstimate`. Encountering NO DATA makes the aggregation result NO DATA unless `ignoreNoData` is `true`.
    """
    # data type: MinAggregation
    oneof_schema_1_validator: Optional[MinAggregation] = None
    # data type: MaxAggregation
    oneof_schema_2_validator: Optional[MaxAggregation] = None
    # data type: FirstAggregation
    oneof_schema_3_validator: Optional[FirstAggregation] = None
    # data type: LastAggregation
    oneof_schema_4_validator: Optional[LastAggregation] = None
    # data type: MeanAggregation
    oneof_schema_5_validator: Optional[MeanAggregation] = None
    # data type: SumAggregation
    oneof_schema_6_validator: Optional[SumAggregation] = None
    # data type: CountAggregation
    oneof_schema_7_validator: Optional[CountAggregation] = None
    # data type: PercentileEstimateAggregation
    oneof_schema_8_validator: Optional[PercentileEstimateAggregation] = None
    actual_instance: Optional[Union[CountAggregation, FirstAggregation, LastAggregation, MaxAggregation, MeanAggregation, MinAggregation, PercentileEstimateAggregation, SumAggregation]] = None
    one_of_schemas: Set[str] = { "CountAggregation", "FirstAggregation", "LastAggregation", "MaxAggregation", "MeanAggregation", "MinAggregation", "PercentileEstimateAggregation", "SumAggregation" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Aggregation.model_construct()
        error_messages = []
        match = 0
        # validate data type: MinAggregation
        if not isinstance(v, MinAggregation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MinAggregation`")
        else:
            match += 1
        # validate data type: MaxAggregation
        if not isinstance(v, MaxAggregation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MaxAggregation`")
        else:
            match += 1
        # validate data type: FirstAggregation
        if not isinstance(v, FirstAggregation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FirstAggregation`")
        else:
            match += 1
        # validate data type: LastAggregation
        if not isinstance(v, LastAggregation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LastAggregation`")
        else:
            match += 1
        # validate data type: MeanAggregation
        if not isinstance(v, MeanAggregation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MeanAggregation`")
        else:
            match += 1
        # validate data type: SumAggregation
        if not isinstance(v, SumAggregation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SumAggregation`")
        else:
            match += 1
        # validate data type: CountAggregation
        if not isinstance(v, CountAggregation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CountAggregation`")
        else:
            match += 1
        # validate data type: PercentileEstimateAggregation
        if not isinstance(v, PercentileEstimateAggregation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PercentileEstimateAggregation`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Aggregation with oneOf schemas: CountAggregation, FirstAggregation, LastAggregation, MaxAggregation, MeanAggregation, MinAggregation, PercentileEstimateAggregation, SumAggregation. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Aggregation with oneOf schemas: CountAggregation, FirstAggregation, LastAggregation, MaxAggregation, MeanAggregation, MinAggregation, PercentileEstimateAggregation, SumAggregation. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into MinAggregation
        try:
            instance.actual_instance = MinAggregation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MaxAggregation
        try:
            instance.actual_instance = MaxAggregation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FirstAggregation
        try:
            instance.actual_instance = FirstAggregation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LastAggregation
        try:
            instance.actual_instance = LastAggregation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MeanAggregation
        try:
            instance.actual_instance = MeanAggregation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SumAggregation
        try:
            instance.actual_instance = SumAggregation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CountAggregation
        try:
            instance.actual_instance = CountAggregation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PercentileEstimateAggregation
        try:
            instance.actual_instance = PercentileEstimateAggregation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Aggregation with oneOf schemas: CountAggregation, FirstAggregation, LastAggregation, MaxAggregation, MeanAggregation, MinAggregation, PercentileEstimateAggregation, SumAggregation. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Aggregation with oneOf schemas: CountAggregation, FirstAggregation, LastAggregation, MaxAggregation, MeanAggregation, MinAggregation, PercentileEstimateAggregation, SumAggregation. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CountAggregation, FirstAggregation, LastAggregation, MaxAggregation, MeanAggregation, MinAggregation, PercentileEstimateAggregation, SumAggregation]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


