# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Link(BaseModel):
    """
    Hyperlink to enable Hypermedia Access
    """ # noqa: E501
    href: StrictStr = Field(description="Supplies the URI to a remote resource (or resource fragment).")
    rel: StrictStr = Field(description="The type or semantics of the relation.")
    type: Optional[StrictStr] = Field(default=None, description="A hint indicating what the media type of the result of dereferencing the link should be.")
    templated: Optional[StrictBool] = Field(default=None, description="This flag set to true if the link is a URL template.")
    var_base: Optional[StrictStr] = Field(default=None, description="A base path to retrieve semantic information about the variables used in URL template.", alias="varBase")
    hreflang: Optional[StrictStr] = Field(default=None, description="A hint indicating what the language of the result of dereferencing the link should be.")
    title: Optional[StrictStr] = Field(default=None, description="Used to label the destination of a link such that it can be used as a human-readable identifier.")
    length: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["href", "rel", "type", "templated", "varBase", "hreflang", "title", "length"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Link from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Link from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "href": obj.get("href"),
            "rel": obj.get("rel"),
            "type": obj.get("type"),
            "templated": obj.get("templated"),
            "varBase": obj.get("varBase"),
            "hreflang": obj.get("hreflang"),
            "title": obj.get("title"),
            "length": obj.get("length")
        })
        return _obj


