# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from geoengine_api_client.models.access_constraints import AccessConstraints
from geoengine_api_client.models.bounding_box2_d import BoundingBox2D
from geoengine_api_client.models.geospatial_data import GeospatialData
from geoengine_api_client.models.geospatial_data_data_type import GeospatialDataDataType
from geoengine_api_client.models.link import Link
from geoengine_api_client.models.style import Style
from geoengine_api_client.models.tile_matrix_limits import TileMatrixLimits
from geoengine_api_client.models.tile_point import TilePoint
from geoengine_api_client.models.tiles_crs import TilesCrs
from typing import Optional, Set
from typing_extensions import Self

class TileSet(BaseModel):
    """
    A resource describing a tileset based on the OGC TileSet Metadata Standard. At least one of the 'TileMatrixSet',  or a link with 'rel' tiling-scheme\"
    """ # noqa: E501
    title: Optional[StrictStr] = Field(default=None, description="A title for this tileset")
    description: Optional[StrictStr] = Field(default=None, description="Brief narrative description of this tile set")
    keywords: Optional[List[StrictStr]] = Field(default=None, description="Unordered list of one or more commonly used or formalized word(s) or phrase(s) used to describe a TileSet")
    data_type: GeospatialDataDataType = Field(alias="dataType")
    tile_matrix_set_uri: Optional[StrictStr] = Field(default=None, description="Reference to a Tile Matrix Set on the OGC NA definition server (<http://www.opengis.net/def/tms/>). Required if the tile matrix set is registered on the definition server.", alias="tileMatrixSetURI")
    tile_matrix_set_limits: Optional[List[TileMatrixLimits]] = Field(default=None, description="Limits for the TileRow and TileCol values for each TileMatrix in the TileMatrixSet. If missing, there are no limits other that the ones imposed by the TileMatrixSet. If present the TileMatrices listed are limited and the rest not available at all", alias="tileMatrixSetLimits")
    crs: TilesCrs = Field(description="Coordinate Reference System (CRS)")
    epoch: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Epoch of the Coordinate Reference System (CRS)")
    links: List[Link] = Field(description="Links to related resources. Possible link 'rel' values are: 'dataset' for a URL pointing to the dataset, 'tiles' for a URL template to get the tiles; 'alternate' for a URL pointing to another representation of the TileSetMetadata (e.g a TileJSON file); 'tiling-scheme' for a definition of the TileMatrixSet")
    layers: Optional[Annotated[List[GeospatialData], Field(min_length=1)]] = None
    bounding_box: Optional[BoundingBox2D] = Field(default=None, description="Minimum bounding rectangle surrounding the tile matrix set, in the supported CRS", alias="boundingBox")
    center_point: Optional[TilePoint] = Field(default=None, description="Location of a tile that nicely represents the tileset. Implementations may use this center value to set the default location or to present a representative tile in a user interface", alias="centerPoint")
    style: Optional[Style] = Field(default=None, description="Style involving all layers used to generate the tileset")
    attribution: Optional[StrictStr] = Field(default=None, description="Short reference to recognize the author or provider")
    license: Optional[StrictStr] = Field(default=None, description="License applicable to the tiles")
    access_constraints: Optional[AccessConstraints] = Field(default=None, description="Restrictions on the availability of the Tile Set that the user needs to be aware of before using or redistributing the Tile Set", alias="accessConstraints")
    version: Optional[StrictStr] = Field(default=None, description="Version of the Tile Set. Changes if the data behind the tiles has been changed")
    created: Optional[datetime] = Field(default=None, description="When the Tile Set was first produced")
    updated: Optional[datetime] = Field(default=None, description="Last Tile Set change/revision")
    point_of_contact: Optional[StrictStr] = Field(default=None, description="Useful information to contact the authors or custodians for the Tile Set", alias="pointOfContact")
    media_types: Optional[List[StrictStr]] = Field(default=None, description="Media types available for the tiles", alias="mediaTypes")
    __properties: ClassVar[List[str]] = ["title", "description", "keywords", "dataType", "tileMatrixSetURI", "tileMatrixSetLimits", "crs", "epoch", "links", "layers", "boundingBox", "centerPoint", "style", "attribution", "license", "accessConstraints", "version", "created", "updated", "pointOfContact", "mediaTypes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TileSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data_type
        if self.data_type:
            _dict['dataType'] = self.data_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tile_matrix_set_limits (list)
        _items = []
        if self.tile_matrix_set_limits:
            for _item_tile_matrix_set_limits in self.tile_matrix_set_limits:
                if _item_tile_matrix_set_limits:
                    _items.append(_item_tile_matrix_set_limits.to_dict())
            _dict['tileMatrixSetLimits'] = _items
        # override the default output from pydantic by calling `to_dict()` of crs
        if self.crs:
            _dict['crs'] = self.crs.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item_links in self.links:
                if _item_links:
                    _items.append(_item_links.to_dict())
            _dict['links'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in layers (list)
        _items = []
        if self.layers:
            for _item_layers in self.layers:
                if _item_layers:
                    _items.append(_item_layers.to_dict())
            _dict['layers'] = _items
        # override the default output from pydantic by calling `to_dict()` of bounding_box
        if self.bounding_box:
            _dict['boundingBox'] = self.bounding_box.to_dict()
        # override the default output from pydantic by calling `to_dict()` of center_point
        if self.center_point:
            _dict['centerPoint'] = self.center_point.to_dict()
        # override the default output from pydantic by calling `to_dict()` of style
        if self.style:
            _dict['style'] = self.style.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TileSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description": obj.get("description"),
            "keywords": obj.get("keywords"),
            "dataType": GeospatialDataDataType.from_dict(obj["dataType"]) if obj.get("dataType") is not None else None,
            "tileMatrixSetURI": obj.get("tileMatrixSetURI"),
            "tileMatrixSetLimits": [TileMatrixLimits.from_dict(_item) for _item in obj["tileMatrixSetLimits"]] if obj.get("tileMatrixSetLimits") is not None else None,
            "crs": TilesCrs.from_dict(obj["crs"]) if obj.get("crs") is not None else None,
            "epoch": obj.get("epoch"),
            "links": [Link.from_dict(_item) for _item in obj["links"]] if obj.get("links") is not None else None,
            "layers": [GeospatialData.from_dict(_item) for _item in obj["layers"]] if obj.get("layers") is not None else None,
            "boundingBox": BoundingBox2D.from_dict(obj["boundingBox"]) if obj.get("boundingBox") is not None else None,
            "centerPoint": TilePoint.from_dict(obj["centerPoint"]) if obj.get("centerPoint") is not None else None,
            "style": Style.from_dict(obj["style"]) if obj.get("style") is not None else None,
            "attribution": obj.get("attribution"),
            "license": obj.get("license"),
            "accessConstraints": obj.get("accessConstraints"),
            "version": obj.get("version"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "pointOfContact": obj.get("pointOfContact"),
            "mediaTypes": obj.get("mediaTypes")
        })
        return _obj


