POST http://localhost:3030/user
Content-Type: application/json

{
  "email": "foo@bar.de",
  "password": "secret123",
  "real_name": "Foo Bar"
}

###

POST http://localhost:3030/login
Content-Type: application/json

{
  "email": "foo@bar.de",
  "password": "secret123"
}

###

POST http://localhost:3030/anonymous
Content-Type: application/json

###

GET http://localhost:3030/session
Authorization: Bearer f8ee09eb-f574-4a08-8c89-d3f60a4f7fd2
Content-Type: application/json

{
  "email": "foo@bar.de",
  "password": "secret123"
}


###

POST http://localhost:3030/login
Content-Type: application/json

{
  "email": "foo@bar.de",
  "password": "wrong"
}

###

POST http://localhost:3030/logout
Content-Type: application/json


###

POST http://localhost:3030/logout
Authorization: Bearer 6cb2191f-0a4d-4ac9-8f92-738e7bed443b
Content-Type: application/json

###

POST http://localhost:3030/project
Authorization: Bearer 6cb2191f-0a4d-4ac9-8f92-738e7bed443b
Content-Type: application/json

{
  "name": "Test",
  "description": "Foobar",
  "bounds": {
    "spatial_reference": "EPSG:4326",
    "bounding_box": {
      "lower_left_coordinate": {
        "x": -180,
        "y": -90
      },
      "upper_right_coordinate": {
        "x": 180,
        "y": 90
      }
    },
    "time_interval": {
      "start": 0,
      "end": 0
    }
  }
}

###

GET http://localhost:3030/projects
Authorization: Bearer 6d69326e-8694-4ae5-815a-b4b1ef02a8f6
Content-Type: application/json

{
  "permissions": [
    "Owner"
  ],
  "filter": "None",
  "order": "NameAsc",
  "offset": 0,
  "limit": 1
}

###

POST http://localhost:3030/workflow
Authorization: Bearer 6d69326e-8694-4ae5-815a-b4b1ef02a8f6
Content-Type: application/json

{
  "type": "Vector",
  "operator": {
    "type": "MockPointSource",
    "params": {
      "points": [
        {
          "x": 1.0,
          "y": 2.0
        },
        {
          "x": 1.0,
          "y": 2.0
        },
        {
          "x": 1.0,
          "y": 2.0
        }
      ]
    }
  }
}

###

GET http://localhost:3030/workflow/9cd4605c-2217-5dda-a286-6c6e0de3468c
Authorization: Bearer 6d69326e-8694-4ae5-815a-b4b1ef02a8f6
Accept: application/json

###

GET http://localhost:3030/workflow/1
Accept: application/json

###

POST http://localhost:3030/workflow
Authorization: Bearer d522fa38-c0e2-44f0-b269-bbadc6806541
Content-Type: application/json

{
  "type": "Vector",
  "operator": {
    "type": "OgrSource",
    "params": {
      "data_set": {
        "Internal": "e3fc70fc-5fbc-41e9-9e7a-3d6ac27e12a9"
      }
    }
  }
}

###

GET http://localhost:3030/wfs?request=GetFeature&service=WFS&version=2.0.0&bbox=-90,-180,90,180&crs=EPSG:4326&typeNames=registry:07968e99-e100-557e-ab4d-08fcdc7d8ff8
Authorization: Bearer d522fa38-c0e2-44f0-b269-bbadc6806541
Content-Type: application/json

###

GET http://localhost:3030/datasets/internal
Authorization: Bearer d522fa38-c0e2-44f0-b269-bbadc6806541
Content-Type: application/json

{
  "order": "NameAsc",
  "offset": 0,
  "limit": 5
}

###
