POST http://localhost:3030/user
Content-Type: application/json

{
  "email": "foo@example.com",
  "password": "secret123",
  "realName": "Foo Bar"
}

###

POST http://localhost:3030/login
Content-Type: application/json

{
  "email": "foo@example.com",
  "password": "secret123"
}

###

# @name anonymousSession
POST http://localhost:3030/anonymous
Content-Type: application/json

###

GET http://localhost:3030/ebv/dataset/10/subdatasets
Authorization: Bearer cc708c33-1571-4cf4-b892-9d7afe93ffde
Accept: application/json


###

GET http://localhost:3030/session
Authorization: Bearer c04e0cd9-e7a9-476c-b201-521db83da0ce
Content-Type: application/json

{
  "email": "foo@example.com",
  "password": "secret123"
}


###

POST http://localhost:3030/login
Content-Type: application/json

{
  "email": "foo@example.com",
  "password": "wrong"
}

###

POST http://localhost:3030/logout
Content-Type: application/json


###

POST http://localhost:3030/logout
Authorization: Bearer 6cb2191f-0a4d-4ac9-8f92-738e7bed443b
Content-Type: application/json

###

POST http://localhost:3030/project
Authorization: Bearer 6cb2191f-0a4d-4ac9-8f92-738e7bed443b
Content-Type: application/json

{
  "name": "Test",
  "description": "Foobar",
  "bounds": {
    "spatialReference": "EPSG:4326",
    "boundingBox": {
      "lowerLeftCoordinate": {
        "x": -180,
        "y": -90
      },
      "upperRightCoordinate": {
        "x": 180,
        "y": 90
      }
    },
    "timeInterval": {
      "start": 0,
      "end": 0
    }
  }
}

###

GET http://localhost:3030/projects?permissions=["Owner"]&filter=None&order=NameAsc&offset=0&limit=1
Authorization: Bearer 6d69326e-8694-4ae5-815a-b4b1ef02a8f6
Content-Type: application/json


### 

# @name getVectorWorkflow
POST http://localhost:3030/workflow
Authorization: Bearer {{anonymousSession.response.body.$.id}}
Content-Type: application/json

{
  "type": "Vector",
  "operator": {
    "type": "MockPointSource",
    "params": {
      "points": [
        {
          "x": 1.0,
          "y": 2.0
        },
        {
          "x": 1.0,
          "y": 2.0
        },
        {
          "x": 1.0,
          "y": 2.0
        }
      ]
    }
  }
}

###

GET http://localhost:3030/workflow/{{getVectorWorkflow.response.body.$.id}}/allMetadata/zip
Authorization: Bearer {{anonymousSession.response.body.$.id}}
Content-Type: application/json

###

GET http://localhost:3030/workflow/9cd4605c-2217-5dda-a286-6c6e0de3468c
Authorization: Bearer 6d69326e-8694-4ae5-815a-b4b1ef02a8f6
Accept: application/json

###

GET http://localhost:3030/workflow/1
Accept: application/json

###

GET http://localhost:3030/datasets?order=NameDesc&offset=0&limit=2
Authorization: Bearer a02187ef-0ddc-4d37-90b8-55d1e05ba47b
Accept: application/json

###

GET http://localhost:3030/providers?order=NameDesc&offset=0&limit=2
Authorization: Bearer 7d82fc9e-ef0d-4c53-a12d-faa309b4b3e4
Accept: application/json

###

GET http://localhost:3030/datasets/external/d0535f1d-27b6-4982-b2f8-b1070f1bf6ee?order=NameDesc&offset=0&limit=2
Authorization: Bearer 7d82fc9e-ef0d-4c53-a12d-faa309b4b3e4
Accept: application/json

###


POST http://localhost:3030/workflow
Authorization: Bearer 89960ca7-94b3-4630-9469-4338231343c4
Content-Type: application/json

{
  "type": "Vector",
  "operator": {
    "type": "MockDatasetDataSource",
    "params": {
      "dataset": {
        "external": {
          "providerId": "d0535f1d-27b6-4982-b2f8-b1070f1bf6ee",
          "datasetId": "d89f1327-15ff-4016-8c3e-e96a7c60d93b"
        }
      }
    }
  }
}


###

GET http://localhost:3030/wfs?request=GetFeature&service=WFS&version=2.0.0&typeNames=registry:ca6e5cb9-51bd-5e78-a723-ab2613457b33&bbox=-90,-180,90,180&srsName=EPSG:4326&time02014-04-01T12:00:00.000Z/2014-04-01T12:00:00.000Z
Authorization: Bearer 7d82fc9e-ef0d-4c53-a12d-faa309b4b3e4
Accept: application/json

###

POST http://localhost:3030/anonymous
Content-Type: application/json

###

POST http://localhost:3030/droneMapping/task
Authorization: Bearer 985bca25-f540-469f-84d8-591936a63d85
Content-Type: application/json

{
  "upload": "61ca657e-6617-4d54-85d0-d11f6d6f9a6f"
}


###

POST http://localhost:3030/droneMapping/dataset/24d488a6-1dcd-4d69-a91a-a3e74493bbdc
Authorization: Bearer 985bca25-f540-469f-84d8-591936a63d85
Accept: application/json

###

GET http://localhost:3000/task/10a0e95b-ecf7-499b-96dd-dc7760e2ade/download/all.zip

###

POST http://localhost:3000/task/new/init


###

POST http://localhost:3000/task/new/upload/530a6809-34c0-457f-8cb9-52c7b89f1ad6

###

###

# @name lastTask
PUT http://localhost:3030/ebv/overviews/all
Authorization: Bearer 8aca8875-425a-4ef1-8ee6-cdfc62dd7525
Accept: application/json

###

# @name lastTask
PUT http://localhost:3030/ebv/overviews/dataset_sm.nc
Authorization: Bearer 8aca8875-425a-4ef1-8ee6-cdfc62dd7525
Content-Type: application/json
Accept: application/json

###

GET http://localhost:3030/tasks/{{lastTask.response.body.$.task_id}}/status
Authorization: Bearer {{anonymousSession.response.body.$.id}}

###

# @name lastTask
DELETE http://localhost:3030/ebv/overviews/dataset_sm.nc
Authorization: Bearer 8aca8875-425a-4ef1-8ee6-cdfc62dd7525
Content-Type: application/json
Accept: application/json

###