mod common '../common.justfile'

_default:
    @just --list

[group("install")]
install: common::_clear
    npm ci

[group("install")]
upgrade: common::_clear
    npx @astrojs/upgrade
    npm update

[group("build")]
build: common::_clear
    npm run build

# Serve the website in development mode with hot reloading, or start the preview server if the "--preview" flag. Usage: `just run` or `just run --preview`
[arg("preview", long="preview", value="true", help="Whether to start the preview instead of the dev server.")]
[group("run")]
run preview="false": common::_clear
    {{ if preview == "true" { "npm run build && npm run preview" } else { "npm run dev" } }}

lint: common::_clear format
    npm run eslint

[arg("write", long="write", value="true", help="Whether to write the formatted files back to disk.")]
[group("lint")]
format write="false": common::_clear
    npx prettier {{ if write == "true" { "--write" } else { "--check" } }} .

test:
