/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddLayer {
    #[serde(rename = "description")]
    pub description: String,
    /// metadata used for loading the data
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "name")]
    pub name: String,
    /// properties, for instance, to be rendered in the UI
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<Vec<String>>>,
    #[serde(rename = "symbology", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub symbology: Option<Option<Box<models::Symbology>>>,
    #[serde(rename = "workflow")]
    pub workflow: Box<models::Workflow>,
}

impl AddLayer {
    pub fn new(description: String, name: String, workflow: models::Workflow) -> AddLayer {
        AddLayer {
            description,
            metadata: None,
            name,
            properties: None,
            symbology: None,
            workflow: Box::new(workflow),
        }
    }
}

