/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AttributeAggregateType {
    #[serde(rename = "meanNumber")]
    MeanNumber,
    #[serde(rename = "stringSample")]
    StringSample,
    #[serde(rename = "null")]
    Null,

}

impl std::fmt::Display for AttributeAggregateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MeanNumber => write!(f, "meanNumber"),
            Self::StringSample => write!(f, "stringSample"),
            Self::Null => write!(f, "null"),
        }
    }
}

impl Default for AttributeAggregateType {
    fn default() -> AttributeAggregateType {
        Self::MeanNumber
    }
}

