/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BandwiseExpressionParameters {
    /// Scalar expression applied to each band value.
    #[serde(rename = "expression")]
    pub expression: String,
    /// Output raster data type for the computed band values.
    #[serde(rename = "outputType")]
    pub output_type: models::RasterDataType,
    /// Whether NO DATA values should be mapped with the expression. Otherwise, they are mapped automatically to NO DATA.
    #[serde(rename = "mapNoData")]
    pub map_no_data: bool,
}

impl BandwiseExpressionParameters {
    pub fn new(expression: String, output_type: models::RasterDataType, map_no_data: bool) -> BandwiseExpressionParameters {
        BandwiseExpressionParameters {
            expression,
            output_type,
            map_no_data,
        }
    }
}

