/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BoxPlot : The `BoxPlot` is a _plot operator_ that computes a box plot over  - a selection of numerical columns of a single vector dataset, or - multiple raster datasets.  Thereby, the operator considers all data in the given query rectangle.  The boxes of the plot span the 1st and 3rd quartile and highlight the median. The whiskers indicate the minimum and maximum values of the corresponding attribute or raster.  ## Errors  The operator returns an error in the following cases.  - Vector data: The `attribute` for one of the given `columnNames` is not numeric. - Vector data: The `attribute` for one of the given `columnNames` does not exist. - Raster data: The length of the `columnNames` parameter does not match the number of input rasters.  ## Notes  If your dataset contains `infinite` or `NAN` values, they are ignored for the computation. Moreover, if your dataset contains more than `10.000`values (which is likely for rasters), the median and quartiles are estimated using the P^2 algorithm described in:  R. Jain and I. Chlamtac, The P^2 algorithm for dynamic calculation of quantiles and histograms without storing observations, Communications of the ACM, Volume 28 (October), Number 10, 1985, p. 1076-1085. <https://www.cse.wustl.edu/~jain/papers/ftp/psqr.pdf>
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoxPlot {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "params")]
    pub params: Box<models::BoxPlotParameters>,
    #[serde(rename = "sources")]
    pub sources: Box<models::MultipleRasterOrSingleVectorSource>,
}

impl BoxPlot {
    /// The `BoxPlot` is a _plot operator_ that computes a box plot over  - a selection of numerical columns of a single vector dataset, or - multiple raster datasets.  Thereby, the operator considers all data in the given query rectangle.  The boxes of the plot span the 1st and 3rd quartile and highlight the median. The whiskers indicate the minimum and maximum values of the corresponding attribute or raster.  ## Errors  The operator returns an error in the following cases.  - Vector data: The `attribute` for one of the given `columnNames` is not numeric. - Vector data: The `attribute` for one of the given `columnNames` does not exist. - Raster data: The length of the `columnNames` parameter does not match the number of input rasters.  ## Notes  If your dataset contains `infinite` or `NAN` values, they are ignored for the computation. Moreover, if your dataset contains more than `10.000`values (which is likely for rasters), the median and quartiles are estimated using the P^2 algorithm described in:  R. Jain and I. Chlamtac, The P^2 algorithm for dynamic calculation of quantiles and histograms without storing observations, Communications of the ACM, Volume 28 (October), Number 10, 1985, p. 1076-1085. <https://www.cse.wustl.edu/~jain/papers/ftp/psqr.pdf>
    pub fn new(r#type: Type, params: models::BoxPlotParameters, sources: models::MultipleRasterOrSingleVectorSource) -> BoxPlot {
        BoxPlot {
            r#type,
            params: Box::new(params),
            sources: Box::new(sources),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "BoxPlot")]
    BoxPlot,
}

impl Default for Type {
    fn default() -> Type {
        Self::BoxPlot
    }
}

