/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClassHistogram : The `ClassHistogram` is a _plot operator_ that computes a histogram plot either over categorical attributes of a vector dataset or categorical values of a raster source. The output is a plot in [Vega-Lite](https://vega.github.io/vega-lite/) specification.  For instance, you want to plot the frequencies of the classes of a categorical attribute of a feature collection. Then you can use a class histogram to visualize and assess this.  ## Errors  The operator returns an error if…  - the selected column (`columnName`) does not exist or is not numeric, - the source is a raster and the property `columnName` is set, or - the input [`Measurement`](../datatypes/measurement) is not categorical.  The operator returns an error if  ## Notes  The operator only uses values of the categorical [`Measurement`](../datatypes/measurement). It ignores missing or no-data values and values that are not covered by the [`Measurement`](../datatypes/measurement). 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClassHistogram {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "params")]
    pub params: Box<models::ClassHistogramParameters>,
    #[serde(rename = "sources")]
    pub sources: Box<models::SingleRasterOrVectorSource>,
}

impl ClassHistogram {
    /// The `ClassHistogram` is a _plot operator_ that computes a histogram plot either over categorical attributes of a vector dataset or categorical values of a raster source. The output is a plot in [Vega-Lite](https://vega.github.io/vega-lite/) specification.  For instance, you want to plot the frequencies of the classes of a categorical attribute of a feature collection. Then you can use a class histogram to visualize and assess this.  ## Errors  The operator returns an error if…  - the selected column (`columnName`) does not exist or is not numeric, - the source is a raster and the property `columnName` is set, or - the input [`Measurement`](../datatypes/measurement) is not categorical.  The operator returns an error if  ## Notes  The operator only uses values of the categorical [`Measurement`](../datatypes/measurement). It ignores missing or no-data values and values that are not covered by the [`Measurement`](../datatypes/measurement). 
    pub fn new(r#type: Type, params: models::ClassHistogramParameters, sources: models::SingleRasterOrVectorSource) -> ClassHistogram {
        ClassHistogram {
            r#type,
            params: Box::new(params),
            sources: Box::new(sources),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ClassHistogram")]
    ClassHistogram,
}

impl Default for Type {
    fn default() -> Type {
        Self::ClassHistogram
    }
}

