/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabaseConnectionConfig {
    #[serde(rename = "database")]
    pub database: String,
    #[serde(rename = "host")]
    pub host: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "schema")]
    pub schema: String,
    #[serde(rename = "user")]
    pub user: String,
}

impl DatabaseConnectionConfig {
    pub fn new(database: String, host: String, password: String, port: i32, schema: String, user: String) -> DatabaseConnectionConfig {
        DatabaseConnectionConfig {
            database,
            host,
            password,
            port,
            schema,
            user,
        }
    }
}

