/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DataPath : A data path is a reference to a location where data is stored. It can be a volume, an upload, or an external source. This information is used when turning a relative file path of a `Dataset` file into an absolute file path on the server.
/// A data path is a reference to a location where data is stored. It can be a volume, an upload, or an external source. This information is used when turning a relative file path of a `Dataset` file into an absolute file path on the server.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DataPath {
    DataPathVolume(Box<models::DataPathVolume>),
    DataPathUpload(Box<models::DataPathUpload>),
    DataPathExternal(String),
}

impl Default for DataPath {
    fn default() -> Self {
        Self::DataPathVolume(Default::default())
    }
}

