/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataUsageSummary {
    #[serde(rename = "count")]
    pub count: i64,
    #[serde(rename = "data")]
    pub data: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl DataUsageSummary {
    pub fn new(count: i64, data: String, timestamp: String) -> DataUsageSummary {
        DataUsageSummary {
            count,
            data,
            timestamp,
        }
    }
}

