/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DataPath {
    DataPathVolume(Box<models::DataPathVolume>),
    DataPathUpload(Box<models::DataPathUpload>),
}

impl Default for DataPath {
    fn default() -> Self {
        Self::DataPathVolume(Default::default())
    }
}

