/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownsamplingResolutionFraction {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Scaling factor in x/y direction.
    #[serde(rename = "x")]
    pub x: f64,
    #[serde(rename = "y")]
    pub y: f64,
}

impl DownsamplingResolutionFraction {
    pub fn new(r#type: Type, x: f64, y: f64) -> DownsamplingResolutionFraction {
        DownsamplingResolutionFraction {
            r#type,
            x,
            y,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "fraction")]
    Fraction,
}

impl Default for Type {
    fn default() -> Type {
        Self::Fraction
    }
}

