/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EdrDataProviderDefinition {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<i32>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "baseUrl")]
    pub base_url: String,
    #[serde(rename = "vectorSpec", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vector_spec: Option<Option<Box<models::EdrVectorSpec>>>,
    #[serde(rename = "cacheTtl", skip_serializing_if = "Option::is_none")]
    pub cache_ttl: Option<i32>,
    /// List of vertical reference systems with a discrete scale
    #[serde(rename = "discreteVrs", skip_serializing_if = "Option::is_none")]
    pub discrete_vrs: Option<Vec<String>>,
    #[serde(rename = "provenance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub provenance: Option<Option<Vec<models::Provenance>>>,
}

impl EdrDataProviderDefinition {
    pub fn new(r#type: Type, name: String, description: String, id: uuid::Uuid, base_url: String) -> EdrDataProviderDefinition {
        EdrDataProviderDefinition {
            r#type,
            name,
            description,
            priority: None,
            id,
            base_url,
            vector_spec: None,
            cache_ttl: None,
            discrete_vrs: None,
            provenance: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Edr")]
    Edr,
}

impl Default for Type {
    fn default() -> Type {
        Self::Edr
    }
}

