/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeatureDataType {
    #[serde(rename = "category")]
    Category,
    #[serde(rename = "int")]
    Int,
    #[serde(rename = "float")]
    Float,
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "bool")]
    Bool,
    #[serde(rename = "dateTime")]
    DateTime,

}

impl std::fmt::Display for FeatureDataType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Category => write!(f, "category"),
            Self::Int => write!(f, "int"),
            Self::Float => write!(f, "float"),
            Self::Text => write!(f, "text"),
            Self::Bool => write!(f, "bool"),
            Self::DateTime => write!(f, "dateTime"),
        }
    }
}

impl Default for FeatureDataType {
    fn default() -> FeatureDataType {
        Self::Category
    }
}

