/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GdalMultiBand {
    #[serde(rename = "resultDescriptor")]
    pub result_descriptor: Box<models::RasterResultDescriptor>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl GdalMultiBand {
    pub fn new(result_descriptor: models::RasterResultDescriptor, r#type: Type) -> GdalMultiBand {
        GdalMultiBand {
            result_descriptor: Box::new(result_descriptor),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "GdalMultiBand")]
    GdalMultiBand,
}

impl Default for Type {
    fn default() -> Type {
        Self::GdalMultiBand
    }
}

