/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GfbioAbcdDataProviderDefinition {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<i32>>,
    #[serde(rename = "dbConfig")]
    pub db_config: Box<models::DatabaseConnectionConfig>,
    #[serde(rename = "cacheTtl", skip_serializing_if = "Option::is_none")]
    pub cache_ttl: Option<i32>,
}

impl GfbioAbcdDataProviderDefinition {
    pub fn new(r#type: Type, name: String, description: String, db_config: models::DatabaseConnectionConfig) -> GfbioAbcdDataProviderDefinition {
        GfbioAbcdDataProviderDefinition {
            r#type,
            name,
            description,
            priority: None,
            db_config: Box::new(db_config),
            cache_ttl: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "GfbioAbcd")]
    GfbioAbcd,
}

impl Default for Type {
    fn default() -> Type {
        Self::GfbioAbcd
    }
}

