/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InterpolationResolution {
    Resolution(Box<models::Resolution>),
    Fraction(Box<models::Fraction>),
}

impl Default for InterpolationResolution {
    fn default() -> Self {
        Self::Resolution(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "resolution")]
    Resolution,
    #[serde(rename = "fraction")]
    Fraction,
}

impl Default for Type {
    fn default() -> Type {
        Self::Resolution
    }
}

