/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinearGradient {
    #[serde(rename = "breakpoints")]
    pub breakpoints: Vec<models::Breakpoint>,
    #[serde(rename = "noDataColor")]
    pub no_data_color: Vec<i32>,
    #[serde(rename = "overColor")]
    pub over_color: Vec<i32>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "underColor")]
    pub under_color: Vec<i32>,
}

impl LinearGradient {
    pub fn new(breakpoints: Vec<models::Breakpoint>, no_data_color: Vec<i32>, over_color: Vec<i32>, r#type: Type, under_color: Vec<i32>) -> LinearGradient {
        LinearGradient {
            breakpoints,
            no_data_color,
            over_color,
            r#type,
            under_color,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "linearGradient")]
    LinearGradient,
}

impl Default for Type {
    fn default() -> Type {
        Self::LinearGradient
    }
}

