/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Link : Hyperlink to enable Hypermedia Access
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Link {
    /// Supplies the URI to a remote resource (or resource fragment).
    #[serde(rename = "href")]
    pub href: String,
    /// The type or semantics of the relation.
    #[serde(rename = "rel")]
    pub rel: String,
    /// A hint indicating what the media type of the result of dereferencing the link should be.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// This flag set to true if the link is a URL template.
    #[serde(rename = "templated", skip_serializing_if = "Option::is_none")]
    pub templated: Option<bool>,
    /// A base path to retrieve semantic information about the variables used in URL template.
    #[serde(rename = "varBase", skip_serializing_if = "Option::is_none")]
    pub var_base: Option<String>,
    /// A hint indicating what the language of the result of dereferencing the link should be.
    #[serde(rename = "hreflang", skip_serializing_if = "Option::is_none")]
    pub hreflang: Option<String>,
    /// Used to label the destination of a link such that it can be used as a human-readable identifier.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<i64>,
}

impl Link {
    /// Hyperlink to enable Hypermedia Access
    pub fn new(href: String, rel: String) -> Link {
        Link {
            href,
            rel,
            r#type: None,
            templated: None,
            var_base: None,
            hreflang: None,
            title: None,
            length: None,
        }
    }
}

