/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlModelInputNoDataHandling {
    #[serde(rename = "variant")]
    pub variant: models::MlModelInputNoDataHandlingVariant,
    #[serde(rename = "noDataValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub no_data_value: Option<Option<f32>>,
}

impl MlModelInputNoDataHandling {
    pub fn new(variant: models::MlModelInputNoDataHandlingVariant) -> MlModelInputNoDataHandling {
        MlModelInputNoDataHandling {
            variant,
            no_data_value: None,
        }
    }
}

