/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Plot {
    #[serde(rename = "workflow")]
    pub workflow: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
}

impl Plot {
    pub fn new(workflow: uuid::Uuid, name: String) -> Plot {
        Plot {
            workflow,
            name,
        }
    }
}

