/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RemoveTileOverlap : The `RemoveTileOverlap` operator crops the overlap halo from all tiles of its input raster.  It is the inverse of `AddTileOverlap`: each tile shrinks symmetrically while its core region and georeference stay untouched. Removing all overlap restores plain tiles that every operator accepts. Use it after ML segmentation to crop model output back to cores.  ## Inputs  The `RemoveTileOverlap` operator expects exactly one _raster_ input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveTileOverlap {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "params")]
    pub params: Box<models::RemoveTileOverlapParameters>,
    #[serde(rename = "sources")]
    pub sources: Box<models::SingleRasterSource>,
}

impl RemoveTileOverlap {
    /// The `RemoveTileOverlap` operator crops the overlap halo from all tiles of its input raster.  It is the inverse of `AddTileOverlap`: each tile shrinks symmetrically while its core region and georeference stay untouched. Removing all overlap restores plain tiles that every operator accepts. Use it after ML segmentation to crop model output back to cores.  ## Inputs  The `RemoveTileOverlap` operator expects exactly one _raster_ input.
    pub fn new(r#type: Type, params: models::RemoveTileOverlapParameters, sources: models::SingleRasterSource) -> RemoveTileOverlap {
        RemoveTileOverlap {
            r#type,
            params: Box::new(params),
            sources: Box::new(sources),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "RemoveTileOverlap")]
    RemoveTileOverlap,
}

impl Default for Type {
    fn default() -> Type {
        Self::RemoveTileOverlap
    }
}

