/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleDescription {
    #[serde(rename = "individual")]
    pub individual: bool,
    #[serde(rename = "role")]
    pub role: Box<models::Role>,
}

impl RoleDescription {
    pub fn new(individual: bool, role: models::Role) -> RoleDescription {
        RoleDescription {
            individual,
            role: Box::new(role),
        }
    }
}

