/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerInfo {
    #[serde(rename = "buildDate")]
    pub build_date: String,
    #[serde(rename = "commitHash")]
    pub commit_hash: String,
    #[serde(rename = "features")]
    pub features: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl ServerInfo {
    pub fn new(build_date: String, commit_hash: String, features: String, version: String) -> ServerInfo {
        ServerInfo {
            build_date,
            commit_hash,
            features,
            version,
        }
    }
}

