/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SingleRasterSource : A single raster operator as a source for this operator.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SingleRasterSource {
    #[serde(rename = "raster")]
    pub raster: Box<models::RasterOperator>,
}

impl SingleRasterSource {
    /// A single raster operator as a source for this operator.
    pub fn new(raster: models::RasterOperator) -> SingleRasterSource {
        SingleRasterSource {
            raster: Box::new(raster),
        }
    }
}

