/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SingleRasterOrVectorSource : A single vector operator or a single raster operators as source for this operator.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SingleRasterOrVectorSource {
    #[serde(rename = "source")]
    pub source: Box<models::SingleRasterOrVectorOperator>,
}

impl SingleRasterOrVectorSource {
    /// A single vector operator or a single raster operators as source for this operator.
    pub fn new(source: models::SingleRasterOrVectorOperator) -> SingleRasterOrVectorSource {
        SingleRasterOrVectorSource {
            source: Box::new(source),
        }
    }
}

