/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpatialBoundsDerive : Spatial bounds derivation options for the [`MockPointSource`].
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SpatialBoundsDerive {
    #[serde(rename="derive")]
    Derive(Box<models::SpatialBoundsDeriveDerive>),
    #[serde(rename="bounds")]
    Bounds(Box<models::SpatialBoundsDeriveBounds>),
    #[serde(rename="none")]
    None(Box<models::SpatialBoundsDeriveNone>),
}

impl Default for SpatialBoundsDerive {
    fn default() -> Self {
        Self::Derive(Default::default())
    }
}


