/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StacProviderS3Config {
    #[serde(rename = "accessKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub access_key: Option<Option<String>>,
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    #[serde(rename = "secretKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret_key: Option<Option<String>>,
}

impl StacProviderS3Config {
    pub fn new(endpoint: String) -> StacProviderS3Config {
        StacProviderS3Config {
            access_key: None,
            endpoint,
            secret_key: None,
        }
    }
}

