/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StacDataProviderDefinition {
    #[serde(rename = "apiUrl")]
    pub api_url: String,
    #[serde(rename = "collectionName")]
    pub collection_name: String,
    #[serde(rename = "datasets")]
    pub datasets: Vec<models::StacProviderDataset>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<i32>>,
    #[serde(rename = "s3Config", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub s3_config: Option<Option<Box<models::StacProviderS3Config>>>,
    #[serde(rename = "timeDimension")]
    pub time_dimension: Box<models::TimeDimension>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl StacDataProviderDefinition {
    pub fn new(api_url: String, collection_name: String, datasets: Vec<models::StacProviderDataset>, description: String, id: uuid::Uuid, name: String, time_dimension: models::TimeDimension, r#type: Type) -> StacDataProviderDefinition {
        StacDataProviderDefinition {
            api_url,
            collection_name,
            datasets,
            description,
            id,
            name,
            priority: None,
            s3_config: None,
            time_dimension: Box::new(time_dimension),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "StacProviderDefinition")]
    StacProviderDefinition,
}

impl Default for Type {
    fn default() -> Type {
        Self::StacProviderDefinition
    }
}

