/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TemporalExtent : The temporal extent of the features in the collection.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemporalExtent {
    /// One or more time intervals that describe the temporal extent of the dataset. The value `null` is supported and indicates an unbounded interval end. In the Core only a single time interval is supported. Extensions may support multiple intervals. If multiple intervals are provided, the union of the intervals describes the temporal extent.
    #[serde(rename = "interval")]
    pub interval: Vec<Vec<String>>,
    /// Coordinate reference system of the coordinates in the temporal extent (property `interval`). The default reference system is the Gregorian calendar. In the Core this is the only supported temporal coordinate reference system. Extensions may support additional temporal coordinate reference systems and add additional enum values.
    #[serde(rename = "trs", skip_serializing_if = "Option::is_none")]
    pub trs: Option<String>,
}

impl TemporalExtent {
    /// The temporal extent of the features in the collection.
    pub fn new(interval: Vec<Vec<String>>) -> TemporalExtent {
        TemporalExtent {
            interval,
            trs: None,
        }
    }
}

