/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TileMatrixSetItem : A minimal tile matrix set element for use within a list of tile matrix sets linking to a full definition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TileMatrixSetItem {
    /// Optional local tile matrix set identifier, e.g. for use as unspecified `{tileMatrixSetId}` parameter. Implementation of 'identifier'
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Box<models::TileMatrixSetId>>,
    /// Title of this tile matrix set, normally used for display to a human
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Reference to an official source for this tileMatrixSet
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "crs", skip_serializing_if = "Option::is_none")]
    pub crs: Option<Box<models::TilesCrs>>,
    /// Links to related resources. A 'self' link to the tile matrix set definition is required.
    #[serde(rename = "links")]
    pub links: Vec<models::Link>,
}

impl TileMatrixSetItem {
    /// A minimal tile matrix set element for use within a list of tile matrix sets linking to a full definition.
    pub fn new(links: Vec<models::Link>) -> TileMatrixSetItem {
        TileMatrixSetItem {
            id: None,
            title: None,
            uri: None,
            crs: None,
            links,
        }
    }
}

