/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimeInterval : Stores time intervals in ms in close-open semantic [start, end)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeInterval {
    #[serde(rename = "start")]
    pub start: i64,
    #[serde(rename = "end")]
    pub end: i64,
}

impl TimeInterval {
    /// Stores time intervals in ms in close-open semantic [start, end)
    pub fn new(start: i64, end: i64) -> TimeInterval {
        TimeInterval {
            start,
            end,
        }
    }
}

