/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateQuota {
    #[serde(rename = "available")]
    pub available: i64,
}

impl UpdateQuota {
    pub fn new(available: i64) -> UpdateQuota {
        UpdateQuota {
            available,
        }
    }
}

