/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VectorJoinParameters {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Column name of the left input used in the join.
    #[serde(rename = "leftColumn")]
    pub left_column: String,
    /// Column name of the right input used in the join.
    #[serde(rename = "rightColumn")]
    pub right_column: String,
    /// Optional suffix added to right-side columns to avoid collisions.
    #[serde(rename = "rightColumnSuffix", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub right_column_suffix: Option<Option<String>>,
}

impl VectorJoinParameters {
    pub fn new(r#type: Type, left_column: String, right_column: String) -> VectorJoinParameters {
        VectorJoinParameters {
            r#type,
            left_column,
            right_column,
            right_column_suffix: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "equiGeoToData")]
    EquiGeoToData,
}

impl Default for Type {
    fn default() -> Type {
        Self::EquiGeoToData
    }
}

