/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VectorOperator : An operator that produces vector data.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VectorOperator {
    #[serde(rename="MockPointSource")]
    MockPointSource(Box<models::MockPointSource>),
    #[serde(rename="OgrSource")]
    OgrSource(Box<models::OgrSource>),
    #[serde(rename="RasterVectorJoin")]
    RasterVectorJoin(Box<models::RasterVectorJoin>),
    #[serde(rename="Reprojection")]
    Reprojection(Box<models::Reprojection>),
    #[serde(rename="VectorExpression")]
    VectorExpression(Box<models::VectorExpression>),
}

impl Default for VectorOperator {
    fn default() -> Self {
        Self::MockPointSource(Default::default())
    }
}


