[package]
name = "geoengine-macros"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true

[features]
pro = []

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
