/*
 * Geo Engine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`wms_handler`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WmsHandlerError {
    UnknownValue(serde_json::Value),
}


pub async fn wms_handler(configuration: &configuration::Configuration, workflow: &str, request: models::WmsRequest, bbox: Option<&str>, bgcolor: Option<&str>, crs: Option<&str>, elevation: Option<&str>, exceptions: Option<&str>, format: Option<&str>, height: Option<i32>, info_format: Option<&str>, layer: Option<&str>, layers: Option<&str>, query_layers: Option<&str>, service: Option<models::WmsService>, sld: Option<&str>, sld_body: Option<&str>, styles: Option<&str>, time: Option<&str>, transparent: Option<bool>, version: Option<&str>, width: Option<i32>) -> Result<reqwest::Response, Error<WmsHandlerError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workflow = workflow;
    let p_query_request = request;
    let p_query_bbox = bbox;
    let p_query_bgcolor = bgcolor;
    let p_query_crs = crs;
    let p_query_elevation = elevation;
    let p_query_exceptions = exceptions;
    let p_query_format = format;
    let p_query_height = height;
    let p_query_info_format = info_format;
    let p_query_layer = layer;
    let p_query_layers = layers;
    let p_query_query_layers = query_layers;
    let p_query_service = service;
    let p_query_sld = sld;
    let p_query_sld_body = sld_body;
    let p_query_styles = styles;
    let p_query_time = time;
    let p_query_transparent = transparent;
    let p_query_version = version;
    let p_query_width = width;

    let uri_str = format!("{}/wms/{workflow}", configuration.base_path, workflow=crate::apis::urlencode(p_path_workflow));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_bbox {
        req_builder = req_builder.query(&[("bbox", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_bgcolor {
        req_builder = req_builder.query(&[("bgcolor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_crs {
        req_builder = req_builder.query(&[("crs", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_elevation {
        req_builder = req_builder.query(&[("elevation", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exceptions {
        req_builder = req_builder.query(&[("exceptions", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_format {
        req_builder = req_builder.query(&[("format", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_height {
        req_builder = req_builder.query(&[("height", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_info_format {
        req_builder = req_builder.query(&[("info_format", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_layer {
        req_builder = req_builder.query(&[("layer", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_layers {
        req_builder = req_builder.query(&[("layers", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_query_layers {
        req_builder = req_builder.query(&[("query_layers", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("request", &p_query_request.to_string())]);
    if let Some(ref param_value) = p_query_service {
        req_builder = req_builder.query(&[("service", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sld {
        req_builder = req_builder.query(&[("sld", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sld_body {
        req_builder = req_builder.query(&[("sld_body", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_styles {
        req_builder = req_builder.query(&[("styles", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_time {
        req_builder = req_builder.query(&[("time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_transparent {
        req_builder = req_builder.query(&[("transparent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_version {
        req_builder = req_builder.query(&[("version", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_width {
        req_builder = req_builder.query(&[("width", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<WmsHandlerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

