mod common '../common.justfile'

_default:
    @just --list

# Install dependencies for app development, building and testing.
[arg("no-lock", long="no-lock", value="true", help="Whether to ignore lock files when installing dependencies.")]
[arg("with-deps", long="with-deps", value="true", help="Whether to install dependencies for Playwright.")]
[group("install")]
install no-lock="false" with-deps="false": common::_clear
    rm -rf node_modules/@geoengine/api-client \
           .angular/cache
    cd ../api-clients/typescript && npm install
    npm link ../api-clients/typescript
    npm {{ if no-lock == "true" { "install" } else { "ci" } }}
    npx playwright install {{ if with-deps == "true" { "--with-deps" } else { "" } }} --only-shell chromium

# Check if justfiles are formatted correctly. Format them with `--write`.
[arg("write", long="write", value="true", help="Whether to write the formatted files back to disk.")]
[group("lint")]
format write="false": common::_clear
    npm run prettier -- {{ if write != "true" { "--check" } else { "--write" } }} .

[arg("project", long="project", help="Whether to only lint a specific project, e.g. `--project=gis`.")]
[arg("fix", long="fix", value="--fix", help="Whether to automatically fix linting errors.")]
[arg("only-errors", long="only-errors", value="--quiet", help="Whether to only print errors and warnings, without the full linting output.")]
lint only-errors="" fix="" project="": common::_clear (format (if fix == "--fix" { "true" } else { "false" }))
    npm run lint -- {{ only-errors }} {{ fix }} {{ project }}

build project="gis": common::_clear
    npm run build-prod:{{ project }}

[arg("type", long="type", help="Run type, e.g., `local` or `nightly`.")]
run project="gis" type="local": common::_clear
    npm run serve:{{ project }}:{{ type }}

[arg("include", long="include", help="Whether to include only specific test files, e.g. `--include=`.")]
[arg("ci", long="ci", value="true", help="Whether to run tests in CI mode.")]
test ci="false" include="" filter="": common::_clear
    npm run test{{ if ci == "true" { ":browser:ci" } else { "" } }} \
        -- \
        {{ if include == "" { "" } else { "--include=" + include } }} \
        {{ if filter == "" { "" } else { '--filter="' + filter + '"' } }}

[group("update")]
update-step1-angular: common::_clear && (lint "--quiet" "--fix" "gis")
    #!/usr/bin/env bash
    LATEST_ANGULAR_VERSION=$(npx @angular/cli@latest version --json | jq -r '.cli.version')
    echo "Updating Angular to version $LATEST_ANGULAR_VERSION"

    npx @angular/cli@latest update --allow-dirty \
        @angular/cli@latest \
        @angular/core@latest \
        @angular/material@latest \
        angular-eslint

update-step2-npm: common::_clear
    npx npm-check-updates -u --target minor
    npm install
