# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.landing_page import LandingPage

class TestLandingPage(unittest.TestCase):
    """LandingPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LandingPage:
        """Test LandingPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LandingPage`
        """
        model = LandingPage()
        if include_optional:
            return LandingPage(
                title = '',
                description = '',
                attribution = '',
                links = [
                    geoengine_api_client.models.link.Link(
                        href = '', 
                        rel = '', 
                        type = '', 
                        templated = True, 
                        var_base = '', 
                        hreflang = '', 
                        title = '', 
                        length = 56, )
                    ]
            )
        else:
            return LandingPage(
        )
        """

    def testLandingPage(self):
        """Test LandingPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
