# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.gdal_meta_data_list import GdalMetaDataList

class TestGdalMetaDataList(unittest.TestCase):
    """GdalMetaDataList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GdalMetaDataList:
        """Test GdalMetaDataList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GdalMetaDataList`
        """
        model = GdalMetaDataList()
        if include_optional:
            return GdalMetaDataList(
                params = [
                    geoengine_api_client.models.gdal_loading_info_temporal_slice.GdalLoadingInfoTemporalSlice(
                        cache_ttl = 0, 
                        params = null, 
                        time = geoengine_api_client.models.time_interval.TimeInterval(
                            end = 56, 
                            start = 56, ), )
                    ],
                result_descriptor = geoengine_api_client.models.raster_result_descriptor.RasterResultDescriptor(
                    bands = [
                        geoengine_api_client.models.raster_band_descriptor.RasterBandDescriptor(
                            measurement = null, 
                            name = '', )
                        ], 
                    data_type = 'U8', 
                    spatial_grid = geoengine_api_client.models.spatial_grid_descriptor.SpatialGridDescriptor(
                        descriptor = 'source', 
                        spatial_grid = geoengine_api_client.models.spatial_grid_definition.SpatialGridDefinition(
                            geo_transform = geoengine_api_client.models.geo_transform.GeoTransform(
                                origin_coordinate = geoengine_api_client.models.coordinate2_d.Coordinate2D(
                                    x = 1.337, 
                                    y = 1.337, ), 
                                x_pixel_size = 1.337, 
                                y_pixel_size = 1.337, ), 
                            grid_bounds = geoengine_api_client.models.grid_bounding_box2_d.GridBoundingBox2D(
                                bottom_right_idx = geoengine_api_client.models.grid_idx2_d.GridIdx2D(
                                    x_idx = 56, 
                                    y_idx = 56, ), 
                                top_left_idx = geoengine_api_client.models.grid_idx2_d.GridIdx2D(
                                    x_idx = 56, 
                                    y_idx = 56, ), ), ), ), 
                    spatial_reference = '', 
                    time = geoengine_api_client.models.time_descriptor.TimeDescriptor(
                        bounds = null, 
                        dimension = null, ), ),
                type = 'GdalMetaDataList'
            )
        else:
            return GdalMetaDataList(
                params = [
                    geoengine_api_client.models.gdal_loading_info_temporal_slice.GdalLoadingInfoTemporalSlice(
                        cache_ttl = 0, 
                        params = null, 
                        time = geoengine_api_client.models.time_interval.TimeInterval(
                            end = 56, 
                            start = 56, ), )
                    ],
                result_descriptor = geoengine_api_client.models.raster_result_descriptor.RasterResultDescriptor(
                    bands = [
                        geoengine_api_client.models.raster_band_descriptor.RasterBandDescriptor(
                            measurement = null, 
                            name = '', )
                        ], 
                    data_type = 'U8', 
                    spatial_grid = geoengine_api_client.models.spatial_grid_descriptor.SpatialGridDescriptor(
                        descriptor = 'source', 
                        spatial_grid = geoengine_api_client.models.spatial_grid_definition.SpatialGridDefinition(
                            geo_transform = geoengine_api_client.models.geo_transform.GeoTransform(
                                origin_coordinate = geoengine_api_client.models.coordinate2_d.Coordinate2D(
                                    x = 1.337, 
                                    y = 1.337, ), 
                                x_pixel_size = 1.337, 
                                y_pixel_size = 1.337, ), 
                            grid_bounds = geoengine_api_client.models.grid_bounding_box2_d.GridBoundingBox2D(
                                bottom_right_idx = geoengine_api_client.models.grid_idx2_d.GridIdx2D(
                                    x_idx = 56, 
                                    y_idx = 56, ), 
                                top_left_idx = geoengine_api_client.models.grid_idx2_d.GridIdx2D(
                                    x_idx = 56, 
                                    y_idx = 56, ), ), ), ), 
                    spatial_reference = '', 
                    time = geoengine_api_client.models.time_descriptor.TimeDescriptor(
                        bounds = null, 
                        dimension = null, ), ),
                type = 'GdalMetaDataList',
        )
        """

    def testGdalMetaDataList(self):
        """Test GdalMetaDataList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
