# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.data_provider_resource import DataProviderResource

class TestDataProviderResource(unittest.TestCase):
    """DataProviderResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataProviderResource:
        """Test DataProviderResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataProviderResource`
        """
        model = DataProviderResource()
        if include_optional:
            return DataProviderResource(
                id = '',
                type = 'provider'
            )
        else:
            return DataProviderResource(
                id = '',
                type = 'provider',
        )
        """

    def testDataProviderResource(self):
        """Test DataProviderResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
