# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.stac_grid import StacGrid

class TestStacGrid(unittest.TestCase):
    """StacGrid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StacGrid:
        """Test StacGrid
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StacGrid`
        """
        model = StacGrid()
        if include_optional:
            return StacGrid(
                target_number_of_cells = 1
            )
        else:
            return StacGrid(
                target_number_of_cells = 1,
        )
        """

    def testStacGrid(self):
        """Test StacGrid"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
