# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.ml_model_name_response import MlModelNameResponse

class TestMlModelNameResponse(unittest.TestCase):
    """MlModelNameResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MlModelNameResponse:
        """Test MlModelNameResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MlModelNameResponse`
        """
        model = MlModelNameResponse()
        if include_optional:
            return MlModelNameResponse(
                ml_model_name = ''
            )
        else:
            return MlModelNameResponse(
                ml_model_name = '',
        )
        """

    def testMlModelNameResponse(self):
        """Test MlModelNameResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
