# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.temporal_raster_aggregation_parameters import TemporalRasterAggregationParameters

class TestTemporalRasterAggregationParameters(unittest.TestCase):
    """TemporalRasterAggregationParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemporalRasterAggregationParameters:
        """Test TemporalRasterAggregationParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemporalRasterAggregationParameters`
        """
        model = TemporalRasterAggregationParameters()
        if include_optional:
            return TemporalRasterAggregationParameters(
                aggregation = None,
                window = geoengine_api_client.models.time_step.TimeStep(
                    granularity = 'millis', 
                    step = 0, ),
                window_reference = 56,
                output_type = 'U8'
            )
        else:
            return TemporalRasterAggregationParameters(
                aggregation = None,
                window = geoengine_api_client.models.time_step.TimeStep(
                    granularity = 'millis', 
                    step = 0, ),
        )
        """

    def testTemporalRasterAggregationParameters(self):
        """Test TemporalRasterAggregationParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
