# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.vector_join_type_equi_geo_to_data import VectorJoinTypeEquiGeoToData

class TestVectorJoinTypeEquiGeoToData(unittest.TestCase):
    """VectorJoinTypeEquiGeoToData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VectorJoinTypeEquiGeoToData:
        """Test VectorJoinTypeEquiGeoToData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VectorJoinTypeEquiGeoToData`
        """
        model = VectorJoinTypeEquiGeoToData()
        if include_optional:
            return VectorJoinTypeEquiGeoToData(
                type = 'equiGeoToData',
                left_column = '',
                right_column = '',
                right_column_suffix = ''
            )
        else:
            return VectorJoinTypeEquiGeoToData(
                type = 'equiGeoToData',
                left_column = '',
                right_column = '',
        )
        """

    def testVectorJoinTypeEquiGeoToData(self):
        """Test VectorJoinTypeEquiGeoToData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
