# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.create_project import CreateProject

class TestCreateProject(unittest.TestCase):
    """CreateProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateProject:
        """Test CreateProject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProject`
        """
        model = CreateProject()
        if include_optional:
            return CreateProject(
                bounds = geoengine_api_client.models.st_rectangle.STRectangle(
                    bounding_box = geoengine_api_client.models.bounding_box2_d.BoundingBox2D(
                        lower_left_coordinate = geoengine_api_client.models.coordinate2_d.Coordinate2D(
                            x = 1.337, 
                            y = 1.337, ), 
                        upper_right_coordinate = geoengine_api_client.models.coordinate2_d.Coordinate2D(
                            x = 1.337, 
                            y = 1.337, ), ), 
                    spatial_reference = '', 
                    time_interval = geoengine_api_client.models.time_interval.TimeInterval(
                        end = 56, 
                        start = 56, ), ),
                description = '',
                name = '',
                time_step = geoengine_api_client.models.time_step.TimeStep(
                    granularity = 'millis', 
                    step = 0, )
            )
        else:
            return CreateProject(
                bounds = geoengine_api_client.models.st_rectangle.STRectangle(
                    bounding_box = geoengine_api_client.models.bounding_box2_d.BoundingBox2D(
                        lower_left_coordinate = geoengine_api_client.models.coordinate2_d.Coordinate2D(
                            x = 1.337, 
                            y = 1.337, ), 
                        upper_right_coordinate = geoengine_api_client.models.coordinate2_d.Coordinate2D(
                            x = 1.337, 
                            y = 1.337, ), ), 
                    spatial_reference = '', 
                    time_interval = geoengine_api_client.models.time_interval.TimeInterval(
                        end = 56, 
                        start = 56, ), ),
                description = '',
                name = '',
        )
        """

    def testCreateProject(self):
        """Test CreateProject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
