# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.sentinel_s2_l2_a_cogs_provider_definition import SentinelS2L2ACogsProviderDefinition

class TestSentinelS2L2ACogsProviderDefinition(unittest.TestCase):
    """SentinelS2L2ACogsProviderDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SentinelS2L2ACogsProviderDefinition:
        """Test SentinelS2L2ACogsProviderDefinition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SentinelS2L2ACogsProviderDefinition`
        """
        model = SentinelS2L2ACogsProviderDefinition()
        if include_optional:
            return SentinelS2L2ACogsProviderDefinition(
                type = 'SentinelS2L2ACogs',
                name = '',
                id = '',
                description = '',
                priority = 56,
                api_url = '',
                stac_api_retries = geoengine_api_client.models.stac_api_retries.StacApiRetries(
                    number_of_retries = 0, 
                    initial_delay_ms = 0, 
                    exponential_backoff_factor = 1.337, ),
                gdal_retries = 0,
                cache_ttl = 0,
                query_buffer = geoengine_api_client.models.stac_query_buffer.StacQueryBuffer(
                    start_seconds = 56, 
                    end_seconds = 56, )
            )
        else:
            return SentinelS2L2ACogsProviderDefinition(
                type = 'SentinelS2L2ACogs',
                name = '',
                id = '',
                description = '',
                api_url = '',
        )
        """

    def testSentinelS2L2ACogsProviderDefinition(self):
        """Test SentinelS2L2ACogsProviderDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
