# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.1
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.histogram_bounds import HistogramBounds

class TestHistogramBounds(unittest.TestCase):
    """HistogramBounds unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistogramBounds:
        """Test HistogramBounds
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistogramBounds`
        """
        model = HistogramBounds()
        if include_optional:
            return HistogramBounds(
                max = 1.337,
                min = 1.337
            )
        else:
            return HistogramBounds(
                max = 1.337,
                min = 1.337,
        )
        """

    def testHistogramBounds(self):
        """Test HistogramBounds"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
