# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.1
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.database_connection_config import DatabaseConnectionConfig

class TestDatabaseConnectionConfig(unittest.TestCase):
    """DatabaseConnectionConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseConnectionConfig:
        """Test DatabaseConnectionConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseConnectionConfig`
        """
        model = DatabaseConnectionConfig()
        if include_optional:
            return DatabaseConnectionConfig(
                database = '',
                host = '',
                password = '',
                port = 0,
                var_schema = '',
                user = ''
            )
        else:
            return DatabaseConnectionConfig(
                database = '',
                host = '',
                password = '',
                port = 0,
                var_schema = '',
                user = '',
        )
        """

    def testDatabaseConnectionConfig(self):
        """Test DatabaseConnectionConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
