# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.1
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.api.plots_api import PlotsApi


class TestPlotsApi(unittest.TestCase):
    """PlotsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlotsApi()

    def tearDown(self) -> None:
        pass

    def test_get_plot_handler(self) -> None:
        """Test case for get_plot_handler

        Generates a plot.
        """
        pass


if __name__ == '__main__':
    unittest.main()
