# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.project_layer import ProjectLayer

class TestProjectLayer(unittest.TestCase):
    """ProjectLayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectLayer:
        """Test ProjectLayer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectLayer`
        """
        model = ProjectLayer()
        if include_optional:
            return ProjectLayer(
                workflow = '',
                name = '',
                visibility = geoengine_api_client.models.layer_visibility.LayerVisibility(
                    data = True, 
                    legend = True, ),
                symbology = None
            )
        else:
            return ProjectLayer(
                workflow = '',
                name = '',
                visibility = geoengine_api_client.models.layer_visibility.LayerVisibility(
                    data = True, 
                    legend = True, ),
                symbology = None,
        )
        """

    def testProjectLayer(self):
        """Test ProjectLayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
