# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.symbology import Symbology

class TestSymbology(unittest.TestCase):
    """Symbology unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Symbology:
        """Test Symbology
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Symbology`
        """
        model = Symbology()
        if include_optional:
            return Symbology(
                opacity = 1.337,
                raster_colorizer = None,
                type = 'raster',
                fill_color = None,
                radius = None,
                stroke = geoengine_api_client.models.stroke_param.StrokeParam(
                    color = null, 
                    width = null, ),
                text = geoengine_api_client.models.text_symbology.TextSymbology(
                    attribute = '', 
                    fill_color = null, 
                    stroke = geoengine_api_client.models.stroke_param.StrokeParam(
                        color = null, 
                        width = null, ), ),
                auto_simplified = True
            )
        else:
            return Symbology(
                opacity = 1.337,
                raster_colorizer = None,
                type = 'raster',
                fill_color = None,
                radius = None,
                stroke = geoengine_api_client.models.stroke_param.StrokeParam(
                    color = null, 
                    width = null, ),
                auto_simplified = True,
        )
        """

    def testSymbology(self):
        """Test Symbology"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
