# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.1
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.gfbio_abcd_data_provider_definition import GfbioAbcdDataProviderDefinition

class TestGfbioAbcdDataProviderDefinition(unittest.TestCase):
    """GfbioAbcdDataProviderDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GfbioAbcdDataProviderDefinition:
        """Test GfbioAbcdDataProviderDefinition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GfbioAbcdDataProviderDefinition`
        """
        model = GfbioAbcdDataProviderDefinition()
        if include_optional:
            return GfbioAbcdDataProviderDefinition(
                cache_ttl = 0,
                db_config = geoengine_api_client.models.database_connection_config.DatabaseConnectionConfig(
                    database = '', 
                    host = '', 
                    password = '', 
                    port = 0, 
                    schema = '', 
                    user = '', ),
                description = '',
                name = '',
                priority = 56,
                type = 'GfbioAbcd'
            )
        else:
            return GfbioAbcdDataProviderDefinition(
                db_config = geoengine_api_client.models.database_connection_config.DatabaseConnectionConfig(
                    database = '', 
                    host = '', 
                    password = '', 
                    port = 0, 
                    schema = '', 
                    user = '', ),
                description = '',
                name = '',
                type = 'GfbioAbcd',
        )
        """

    def testGfbioAbcdDataProviderDefinition(self):
        """Test GfbioAbcdDataProviderDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
