# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.fraction1 import Fraction1

class TestFraction1(unittest.TestCase):
    """Fraction1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Fraction1:
        """Test Fraction1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Fraction1`
        """
        model = Fraction1()
        if include_optional:
            return Fraction1(
                x = 1.337,
                y = 1.337,
                type = 'fraction'
            )
        else:
            return Fraction1(
                x = 1.337,
                y = 1.337,
                type = 'fraction',
        )
        """

    def testFraction1(self):
        """Test Fraction1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
