# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.class_histogram_parameters import ClassHistogramParameters

class TestClassHistogramParameters(unittest.TestCase):
    """ClassHistogramParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClassHistogramParameters:
        """Test ClassHistogramParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClassHistogramParameters`
        """
        model = ClassHistogramParameters()
        if include_optional:
            return ClassHistogramParameters(
                column_name = ''
            )
        else:
            return ClassHistogramParameters(
        )
        """

    def testClassHistogramParameters(self):
        """Test ClassHistogramParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
