# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.aggregation_min import AggregationMin

class TestAggregationMin(unittest.TestCase):
    """AggregationMin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AggregationMin:
        """Test AggregationMin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AggregationMin`
        """
        model = AggregationMin()
        if include_optional:
            return AggregationMin(
                type = 'min',
                ignore_no_data = True
            )
        else:
            return AggregationMin(
                type = 'min',
                ignore_no_data = True,
        )
        """

    def testAggregationMin(self):
        """Test AggregationMin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
