# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.9.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.histogram_buckets_square_root_choice_rule import HistogramBucketsSquareRootChoiceRule

class TestHistogramBucketsSquareRootChoiceRule(unittest.TestCase):
    """HistogramBucketsSquareRootChoiceRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistogramBucketsSquareRootChoiceRule:
        """Test HistogramBucketsSquareRootChoiceRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistogramBucketsSquareRootChoiceRule`
        """
        model = HistogramBucketsSquareRootChoiceRule()
        if include_optional:
            return HistogramBucketsSquareRootChoiceRule(
                max_number_of_buckets = 0,
                type = 'squareRootChoiceRule'
            )
        else:
            return HistogramBucketsSquareRootChoiceRule(
                type = 'squareRootChoiceRule',
        )
        """

    def testHistogramBucketsSquareRootChoiceRule(self):
        """Test HistogramBucketsSquareRootChoiceRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
