# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoengine_api_client.models.raster_type_conversion_parameters import RasterTypeConversionParameters

class TestRasterTypeConversionParameters(unittest.TestCase):
    """RasterTypeConversionParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RasterTypeConversionParameters:
        """Test RasterTypeConversionParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RasterTypeConversionParameters`
        """
        model = RasterTypeConversionParameters()
        if include_optional:
            return RasterTypeConversionParameters(
                output_data_type = 'U8'
            )
        else:
            return RasterTypeConversionParameters(
                output_data_type = 'U8',
        )
        """

    def testRasterTypeConversionParameters(self):
        """Test RasterTypeConversionParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
