name: CI

on:
  pull_request:
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
   contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  geoengine-test:
    name: "geoengine / test"
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      # TODO: Get Cache back
      # - name: setup rust build cache
      #   uses: Swatinem/rust-cache@v2
      #   with:
      #     # An explicit cache key that is used instead of the automatic `job`-based
      #     # cache key and is thus stable across jobs.
      #     # Default: empty
      #     shared-key: ""

      #     # An additional cache key that is added alongside the automatic `job`-based
      #     # cache key and can be used to further differentiate jobs.
      #     # Default: empty
      #     key: ci_test_
      - name: Testsuite
        uses: ./.github/actions/test
      - name: Adjust lcov.info
        # The lcov file is generated in the container and contains absolute paths, so we need to adjust them.
        run: sed -i 's|/github/workspace/||g' geoengine/lcov.info
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: geoengine/lcov.info
          fail-on-error: false # do not fail the workflow if the upload fails

  geoengine-lint:
    name: "geoengine / lint"
    
    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - name: Init rustup toolchain
        # somehow rustup show will take care to initialize the version based on the toolchain file
        run: rustup show
      - name: setup rust build cache
        uses: Swatinem/rust-cache@v2
        with:
          # An explicit cache key that is used instead of the automatic `job`-based
          # cache key and is thus stable across jobs.
          # Default: empty
          shared-key: ""

          # An additional cache key that is added alongside the automatic `job`-based
          # cache key and can be used to further differentiate jobs.
          # Default: empty
          key: ci_test_
      - name: Rustfmt
        run: just backend lint-rustfmt
      - name: Clippy
        run: just backend lint-clippy
      - name: SQLFluff
        run: just backend lint-sql

  geoengine-build:
    name: "geoengine / build"

    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    strategy:
      matrix:
        build: ["", "--release"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - name: Init rustup toolchain
        # somehow rustup show will take care to initialize the version based on the toolchain file
        run: rustup show
      - name: setup rust build cache
        uses: Swatinem/rust-cache@v2
        with:
          # An explicit cache key that is used instead of the automatic `job`-based
          # cache key and is thus stable across jobs.
          # Default: empty
          shared-key: ""

          # An additional cache key that is added alongside the automatic `job`-based
          # cache key and can be used to further differentiate jobs.
          # Default: empty
          key: ci_test_${{ matrix.build }}
      - name: Build
        run: just backend build "${{ matrix.build }}"
  
  python:
    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        # use all supported versions from https://devguide.python.org/versions/
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        uv: [false]
        module-resolution: [""]
        coverage: [false]
        include:
          - python-version: "3.10" # always test the minimum version
            uv: true
            module-resolution: "--resolution=lowest-direct"
            coverage: true

    env:
      USE_UV: ${{ matrix.uv }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        if: ${{ matrix.uv }}
        run: just python install-uv
      - name: Virtual environment
        run: just python install-venv
      - name: Dev dependencies
        run: just python install-dependencies "dev" "${{ matrix.module-resolution }}"
      - name: Lints
        run: just python lint-code
        # TODO: fix issues with mypy and uv
        if: ${{ !matrix.uv }}
      - name: Test dependencies
        run: just python install-dependencies "test" "${{ matrix.module-resolution }}"
      - name: Test Lints
        run: just python lint-tests
        # TODO: fix issues with mypy and uv
        if: ${{ !matrix.uv }}
      - name: Start PostgreSQL
        run: service postgresql start
      - name: Tests
        run: >
          just python test
          --build-type=release
          ${{ matrix.coverage && '--coverage' || '' }}
      - name: Example dependencies
        run: just python install-dependencies "examples" "${{ matrix.module-resolution }}"
      - name: Examples
        run: >
          just python run-examples
          --build-type=release
          ${{ matrix.coverage && '--coverage' || '' }}
      - name: Report coverage to Coveralls
        if: ${{ matrix.coverage }}
        # 1. We need to adjust the paths in the lcov file to match the repository structure.
        # 2. We need to download the coveralls script and upload the report.
        run: |
          sed -i 's|SF:geoengine/|SF:|' ../coverage.lcov
          curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz
          ./coveralls report ../coverage.lcov
        # If we don't run it in the code folder, the paths in the report will prefixed with `library/geoengine/`.
        working-directory: python/geoengine
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}
  
  www:
    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    steps:
        - name: Checkout code
          uses: actions/checkout@v6
        - uses: extractions/setup-just@v4
        - name: Install
          run: just www install
        - name: Check formatting and lints
          run: just www lint
        - name: Build
          run: just www build
        - name: Idempotency check
          run: just common check-no-changes-in-git-repo


  api-client-python:
    name: "api-client / python"

    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate OpenAPI spec
        run: just api-clients test-python

  api-client-typescript:
    name: "api-client / typescript"

    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    strategy:
      matrix:
        node-version: [20.19.x, 22.12.x, 24.0.x]

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build
        run: just api-clients test-typescript

  api-client-rust:
    name: "api-client / rust"

    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - uses: extractions/setup-just@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build and test
        run: just api-clients test-rust

  api-client-idempotency:
    name: "api-client / rust"

    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - name: Install Java (OpenAPI Generator requires Java to run)
        run: |
          # deleted in devcontainer image, but required by java installer
          mkdir -p /usr/share/man/man1
          apt-get update
          apt-get install -y openjdk-21-jre-headless
      - name: Lint OpenAPI specification
        run: just api-clients lint-openapi-spec
      - name: Generate API clients
        run: just api-clients build
      - name: Check for changes in git repo
        run: just common check-no-changes-in-git-repo

  ui-build:
    name: "ui / build"
    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    strategy:
      matrix:
        app:
          - gis
          - manager
          - dashboards/gfbio
          - dashboards/data-atlas
          - dashboards/nfdi-portal-demo
          - dashboards/ebv-analyzer
          - dashboards/ecometrics
          - dashboards/esg-indicator-service
    
    steps:
      - uses: actions/checkout@v5
      - uses: extractions/setup-just@v4
      - name: Install Dependencies
        run: just ui install
      - name: Build app ${{ matrix.app }}
        run: just ui build ${{ matrix.app }}
        env:
          CI: true
  
  ui-test:
    name: "ui / test"
    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - uses: extractions/setup-just@v4
      - name: Install Dependencies
        run: just ui install --with-deps
      - run: just ui test --ci
        env:
          CI: true

  ui-lint:
    name: "ui / lint"

    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: extractions/setup-just@v4
      - name: Install Dependencies
        run: just ui install
      - name: Code Format Check with Prettier
        run: just ui format
      - name: Build common & core
        run: |
          just ui build common
          just ui build core
      - name: Check with Linter
        run: just ui lint

  repository-lint:
    name: "repository / lint"

    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - name: Lint repository-wide formats & versions
        run: just ci repo
