name: CI

on:
  pull_request:
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: setup rust build cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cargo"
          shared-key: "ci"
          key: "k"
          add-job-id-key: "false"
      - name: Testsuite
        uses: ./.github/actions/test
      - name: Adjust lcov.info
        # The lcov file is generated in the container and contains absolute paths, so we need to adjust them.
        run: sed -i 's|/github/workspace/||g' lcov.info
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: lcov.info
          fail-on-error: false # do not fail the workflow if the upload fails

  lint:
    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Init rustup toolchain
        # somehow rustup show will take care to initialize the version based on the toolchain file
        run: rustup show
      - name: setup rust build cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cargo"
          shared-key: "ci"
          key: "k"
          add-job-id-key: "false"
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets --locked -- -D warnings
      - name: SQLFluff
        run: pipx run sqlfluff==4.0.4 lint

  openapi:
    name: OpenAPI Validation

    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Validate OpenAPI spec
        run: npx @openapitools/openapi-generator-cli validate -i openapi.json

  build:
    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    strategy:
      matrix:
        build: ["", "--release"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Init rustup toolchain
        # somehow rustup show will take care to initialize the version based on the toolchain file
        run: rustup show
      - name: setup rust build cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cargo"
          shared-key: "ci"
          key: "k"
          add-job-id-key: "false"
      - name: Build
        run: cargo build --locked ${{ matrix.build }} --verbose
