name: CI

on:
  pull_request:
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      # TODO: Get Cache back
      # - name: setup rust build cache
      #   uses: Swatinem/rust-cache@v2
      #   with:
      #     # An explicit cache key that is used instead of the automatic `job`-based
      #     # cache key and is thus stable across jobs.
      #     # Default: empty
      #     shared-key: ""

      #     # An additional cache key that is added alongside the automatic `job`-based
      #     # cache key and can be used to further differentiate jobs.
      #     # Default: empty
      #     key: ci_test_
      - name: Testsuite
        uses: ./.github/actions/test
      - name: Adjust lcov.info
        # The lcov file is generated in the container and contains absolute paths, so we need to adjust them.
        run: sed -i 's|/github/workspace/||g' geoengine/lcov.info
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: geoengine/lcov.info
          fail-on-error: false # do not fail the workflow if the upload fails

  lint:
    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - name: Init rustup toolchain
        # somehow rustup show will take care to initialize the version based on the toolchain file
        run: rustup show
      - name: setup rust build cache
        uses: Swatinem/rust-cache@v2
        with:
          # An explicit cache key that is used instead of the automatic `job`-based
          # cache key and is thus stable across jobs.
          # Default: empty
          shared-key: ""

          # An additional cache key that is added alongside the automatic `job`-based
          # cache key and can be used to further differentiate jobs.
          # Default: empty
          key: ci_test_
      - name: Rustfmt
        run: just backend lint-rustfmt
      - name: Clippy
        run: just backend lint-clippy
      - name: SQLFluff
        run: just backend lint-sql

  openapi:
    name: OpenAPI Validation

    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - name: Validate OpenAPI spec
        run: just validate-openapi-spec

  build:
    runs-on: ubuntu-24.04
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read

    strategy:
      matrix:
        build: ["", "--release"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - name: Init rustup toolchain
        # somehow rustup show will take care to initialize the version based on the toolchain file
        run: rustup show
      - name: setup rust build cache
        uses: Swatinem/rust-cache@v2
        with:
          # An explicit cache key that is used instead of the automatic `job`-based
          # cache key and is thus stable across jobs.
          # Default: empty
          shared-key: ""

          # An additional cache key that is added alongside the automatic `job`-based
          # cache key and can be used to further differentiate jobs.
          # Default: empty
          key: ci_test_${{ matrix.build }}
      - name: Build
        run: just backend build "${{ matrix.build }}"
  
  python:
    uses: ./.github/workflows/test-python.yml

    strategy:
      fail-fast: false
      matrix:
        # use all supported versions from https://devguide.python.org/versions/
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    with:
      python-version: ${{ matrix.python-version }}
      use-uv: false
      coverage: false

  # Checks the library using minimum version resolution
  # `uv` has this feature built-in, c.f. https://github.com/astral-sh/uv
  python-min-version:
    uses: ./.github/workflows/test-python.yml

    with:
      python-version: "3.10"
      use-uv: true
      coverage: true
