name: Coverage

on:
  push:
    branches: [master, trying, staging]
  pull_request:
    branches: [master, trying, staging]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Coveralls:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_USER: geoengine
          POSTGRES_PASSWORD: geoengine
          POSTGRES_DB: geoengine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add UbuntuGIS ppa
        run: sudo add-apt-repository ppa:ubuntugis/ppa
      - name: APT update
        run: sudo apt-get update
      - name: Install lld
        run: sudo apt-get install lld
      - name: Install GDAL
        run: |
          sudo apt-get install libgdal-dev gdal-bin build-essential
          export C_INCLUDE_PATH=/usr/include/gdal:$C_INCLUDE_PATH
          export CPLUS_INCLUDE_PATH=/usr/include/gdal:$CPLUS_INCLUDE_PATH
          sudo ldconfig
      - name: Add rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Generate code coverage
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --verbose --workspace --timeout 120 --out Lcov --all-features --run-types Tests
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
