# This workflows builds the libraries and publishes them on PyPI, npm, and crates.io.

name: Build & Publish

on:
  # run on push to main branch if any of the relevant files changed
  push:
    branches:
      - main
    paths:
      - "api-clients/python/setup.py"
      - "api-clients/typescript/package.json"
      - "api-clients/rust/Cargo.toml"
      - "python/pyproject.toml"
      - "geoengine/Cargo.toml"
  
  # schedule manually
  workflow_dispatch:

env:
  python-version: "3.10" # use lowest supported Python version
  node-version: "20.19.x" # use lowest supported Node version
  rust-version: "1.85.1" # use lowest supported Rust version

jobs:
  api-client-python:
    name: Publish Python API Client Package

    runs-on: ubuntu-latest
    container: quay.io/geoengine/devcontainer:latest

    environment:
      name: pypi
      url: https://pypi.org/p/geoengine-api-client

    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v6
      - name: Check if tag is already published
        id: tag
        run: echo "tag_already_published=$(just repo::is-api-client-python-already-published)" >> $GITHUB_OUTPUT
      - name: Skip publish step if version is already published
        if: steps.tag.outputs.tag_already_published == 'true'
        run: echo "Version is already published, skipping publish step."
      - name: Set up Python ${{ env.python-version }}
        if: steps.tag.outputs.tag_already_published == 'false'
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies, build a binary wheel & a source tarball
        if: steps.tag.outputs.tag_already_published == 'false'
        run: just api-clients build-python-dist
      - name: Publish package to PyPI
        if: steps.tag.outputs.tag_already_published == 'false'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: api-clients/python/dist/ # does not use `run.working-directory`

  api-client-typescript:
    name: Publish TypeScript API Client Package

    runs-on: ubuntu-latest
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v6
      - name: Check if tag is already published
        id: tag
        run: echo "tag_already_published=$(just repo is-api-client-typescript-already-published)" >> $GITHUB_OUTPUT
      - name: Skip publish step if version is already published
        if: steps.tag.outputs.tag_already_published == 'true'
        run: echo "Version is already published, skipping publish step."
      - name: Use Node.js ${{ env.node-version }}
        if: steps.tag.outputs.tag_already_published == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies & build
        if: steps.tag.outputs.tag_already_published == 'false'
        run: just api-clients build-typescript-dist
      - name: Publish
        if: steps.tag.outputs.tag_already_published == 'false'
        run: npm publish --access public
        working-directory: api-clients/typescript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  api-client-rust:
    name: Publish Rust API Client Package

    runs-on: ubuntu-latest
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v6
      - name: Check if tag is already published
        id: tag
        run: echo "tag_already_published=$(just repo is-api-client-rust-already-published)" >> $GITHUB_OUTPUT
      - name: Skip publish step if version is already published
        if: steps.tag.outputs.tag_already_published == 'true'
        run: echo "Version is already published, skipping publish step."
      - name: Set up Rust ${{ env.rust-version }}
        if: steps.tag.outputs.tag_already_published == 'false'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust-version }}
      - name: Install dependencies
        if: steps.tag.outputs.tag_already_published == 'false'
        run: just api-clients build-rust-dist
      - uses: rust-lang/crates-io-auth-action@v1
        if: steps.tag.outputs.tag_already_published == 'false'
        id: auth
      - name: Publish
        if: steps.tag.outputs.tag_already_published == 'false'
        run: cargo publish
        working-directory: api-clients/rust
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  python:
    name: Publish Python Package

    runs-on: ubuntu-latest
    container: quay.io/geoengine/devcontainer:latest

    env:
      python-version: "3.10" # use lowest supported Python version

    environment:
      name: pypi
      url: https://pypi.org/p/geoengine

    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v6
      - name: Check if tag is already published
        id: tag
        run: echo "tag_already_published=$(just repo is-python-library-already-published)" >> $GITHUB_OUTPUT
      - name: Skip publish step if version is already published
        if: steps.tag.outputs.tag_already_published == 'true'
        run: echo "Version is already published, skipping publish step."
      - name: Set up Python ${{ env.python-version }}
        if: steps.tag.outputs.tag_already_published == 'false'
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies & build package
        if: steps.tag.outputs.tag_already_published == 'false'
        run: |
          just python install
          just python build
      - name: Publish package to PyPI
        if: steps.tag.outputs.tag_already_published == 'false'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/

  tag:
    name: Publish Git Tag

    runs-on: ubuntu-latest
    container: quay.io/geoengine/devcontainer:latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - name: Store tag and check if tag is already published
        id: tag
        run: |
          echo "tag_already_published=$(just repo is-tag-already-published)" >> $GITHUB_OUTPUT
          echo "version_tag=$(just repo print-version-tag)" >> $GITHUB_OUTPUT
      - name: Skip tag step if tag is already published
        if: steps.tag.outputs.tag_already_published == 'true'
        run: echo "Tag is already published, skipping tag step."
      - name: Create and push git tag
        if: steps.tag.outputs.tag_already_published == 'false'
        uses: actions/github-script@v9
        with:
          script: |
            const versionTag = process.env.VERSION_TAG;

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${versionTag}`,
              sha: context.sha
            });
        env:
          VERSION_TAG: ${{ steps.tag.outputs.version_tag }}
