# This workflows builds the libraries and publishes them on PyPI, npm, and crates.io.

name: Build & Publish

on:
  # run on push to main branch if any of the relevant files changed
  push:
    branches:
      - main
    paths:
      - "api-clients/python/setup.py"
      - "api-clients/typescript/package.json"
      - "api-clients/rust/Cargo.toml"
      - "python/pyproject.toml"
      - "geoengine/Cargo.toml"
  
  # schedule manually
  workflow_dispatch:

jobs:
  api-client-python:
    name: Publish Python API Client Package

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"] # use lowest supported Python version

    defaults:
      run:
        working-directory: api-clients/python

    environment:
      name: pypi
      url: https://pypi.org/p/geoengine-api-client

    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - name: Build a binary wheel and a source tarball
        run: |
          pip install --upgrade build
          python3 -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: api-clients/python/dist/ # does not use `run.working-directory`
          skip-existing: true

  api-client-typescript:
    name: Publish TypeScript API Client Package

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    strategy:
      matrix:
        node-version: [20.19.x] # use lowest supported Node version

    defaults:
      run:
        working-directory: api-clients/typescript

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: |
          if `just repo is-api-client-typescript-already-published`; then
            echo "Version is already published, skipping publish step."
            exit 0
          fi
          
          npm publish --access public
          
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  api-client-rust:
    name: Publish Rust API Client Package

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    strategy:
      matrix:
        rust-version: ["1.80.0"] # use lowest supported Rust version

    defaults:
      run:
        working-directory: api-clients/rust

    steps:
      - uses: actions/checkout@v6
      - name: Set up Rust ${{ matrix.rust-version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Install dependencies
        run: cargo fetch
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish
        run: |
          if `just repo is-api-client-rust-already-published`; then
            echo "Version is already published, skipping publish step."
            exit 0
          fi

          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  python:
    name: Publish Python Package

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"] # use lowest supported Python version

    defaults:
      run:
        working-directory: python

    environment:
      name: pypi
      url: https://pypi.org/p/geoengine

    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: just python install
      - name: Build a binary wheel and a source tarball
        run: just python build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true

  tag:
    name: Publish Git Tag

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - name: Create and push git tag
        run: |
          if `just repo is-tag-already-published`; then
            echo "Tag is already published, skipping tag step."
            exit 0
          fi

          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/`just repo::print-version-tag`",
            sha: context.sha
          })
