/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Collection,
  Collections,
  CollectionsResponseFormat,
  Conformance,
  LandingPage,
  TileMatrixSet,
  TileMatrixSets,
  TileSetMetadataResponse,
  TileSetsResponse,
} from '../models/index';
import {
    CollectionFromJSON,
    CollectionToJSON,
    CollectionsFromJSON,
    CollectionsToJSON,
    CollectionsResponseFormatFromJSON,
    CollectionsResponseFormatToJSON,
    ConformanceFromJSON,
    ConformanceToJSON,
    LandingPageFromJSON,
    LandingPageToJSON,
    TileMatrixSetFromJSON,
    TileMatrixSetToJSON,
    TileMatrixSetsFromJSON,
    TileMatrixSetsToJSON,
    TileSetMetadataResponseFromJSON,
    TileSetMetadataResponseToJSON,
    TileSetsResponseFromJSON,
    TileSetsResponseToJSON,
} from '../models/index';

export interface CollectionRequest {
    processingGraphId: string;
}

export interface CollectionTilesetRequest {
    processingGraphId: string;
    collectionId: string;
    tileMatrixSetId: string;
}

export interface CollectionTilesetsRequest {
    processingGraphId: string;
    collectionId: string;
}

export interface CollectionsRequest {
    processingGraphId: string;
    datetime?: string;
    bbox?: string;
    limit?: number | null;
    f?: CollectionsResponseFormat | null;
}

export interface ConformanceRequest {
    processingGraphId: string;
}

export interface LandingPageRequest {
    processingGraphId: string;
}

export interface TileRequest {
    processingGraphId: string;
    collectionId: string;
    tileMatrixSetId: string;
    tileMatrix: number;
    tileRow: number;
    tileCol: number;
    datetime?: string;
}

export interface TileMatrixSetRequest {
    processingGraphId: string;
    tileMatrixSetId: string;
}

export interface TileMatrixSetsRequest {
    processingGraphId: string;
}

/**
 * 
 */
export class OGCAPIApi extends runtime.BaseAPI {

    /**
     * Creates request options for collection without sending the request
     */
    async collectionRequestOpts(requestParameters: CollectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['processingGraphId'] == null) {
            throw new runtime.RequiredError(
                'processingGraphId',
                'Required parameter "processingGraphId" was null or undefined when calling collection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ogc/ogc/{processingGraphId}/collections/{processingGraphId}`;
        urlPath = urlPath.replace(`{${"processingGraphId"}}`, encodeURIComponent(String(requestParameters['processingGraphId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cf. [OGC API - Common - Part 2: Collections](https://docs.ogc.org/DRAFTS/20-024.html).
     * OGC API Collection Metadata
     */
    async collectionRaw(requestParameters: CollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Collection>> {
        const requestOptions = await this.collectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionFromJSON(jsonValue));
    }

    /**
     * Cf. [OGC API - Common - Part 2: Collections](https://docs.ogc.org/DRAFTS/20-024.html).
     * OGC API Collection Metadata
     */
    async collection(requestParameters: CollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Collection> {
        const response = await this.collectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collectionTileset without sending the request
     */
    async collectionTilesetRequestOpts(requestParameters: CollectionTilesetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['processingGraphId'] == null) {
            throw new runtime.RequiredError(
                'processingGraphId',
                'Required parameter "processingGraphId" was null or undefined when calling collectionTileset().'
            );
        }

        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling collectionTileset().'
            );
        }

        if (requestParameters['tileMatrixSetId'] == null) {
            throw new runtime.RequiredError(
                'tileMatrixSetId',
                'Required parameter "tileMatrixSetId" was null or undefined when calling collectionTileset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ogc/ogc/{processingGraphId}/collections/{collectionId}/tiles/{tileMatrixSetId}`;
        urlPath = urlPath.replace(`{${"processingGraphId"}}`, encodeURIComponent(String(requestParameters['processingGraphId'])));
        urlPath = urlPath.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId'])));
        urlPath = urlPath.replace(`{${"tileMatrixSetId"}}`, encodeURIComponent(String(requestParameters['tileMatrixSetId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cf. [OGC API - Tiles - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html).
     * OGC API Collection Tileset Metadata
     */
    async collectionTilesetRaw(requestParameters: CollectionTilesetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TileSetMetadataResponse>> {
        const requestOptions = await this.collectionTilesetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TileSetMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Cf. [OGC API - Tiles - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html).
     * OGC API Collection Tileset Metadata
     */
    async collectionTileset(requestParameters: CollectionTilesetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TileSetMetadataResponse> {
        const response = await this.collectionTilesetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collectionTilesets without sending the request
     */
    async collectionTilesetsRequestOpts(requestParameters: CollectionTilesetsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['processingGraphId'] == null) {
            throw new runtime.RequiredError(
                'processingGraphId',
                'Required parameter "processingGraphId" was null or undefined when calling collectionTilesets().'
            );
        }

        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling collectionTilesets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ogc/ogc/{processingGraphId}/collections/{collectionId}/tiles`;
        urlPath = urlPath.replace(`{${"processingGraphId"}}`, encodeURIComponent(String(requestParameters['processingGraphId'])));
        urlPath = urlPath.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cf. [OGC API - Tiles - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html).
     * OGC API Collection Tilesets List
     */
    async collectionTilesetsRaw(requestParameters: CollectionTilesetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TileSetsResponse>> {
        const requestOptions = await this.collectionTilesetsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TileSetsResponseFromJSON(jsonValue));
    }

    /**
     * Cf. [OGC API - Tiles - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html).
     * OGC API Collection Tilesets List
     */
    async collectionTilesets(requestParameters: CollectionTilesetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TileSetsResponse> {
        const response = await this.collectionTilesetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for collections without sending the request
     */
    async collectionsRequestOpts(requestParameters: CollectionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['processingGraphId'] == null) {
            throw new runtime.RequiredError(
                'processingGraphId',
                'Required parameter "processingGraphId" was null or undefined when calling collections().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['datetime'] != null) {
            queryParameters['datetime'] = requestParameters['datetime'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['f'] != null) {
            queryParameters['f'] = requestParameters['f'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ogc/ogc/{processingGraphId}/collections`;
        urlPath = urlPath.replace(`{${"processingGraphId"}}`, encodeURIComponent(String(requestParameters['processingGraphId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cf. [OGC API - Common - Part 2: Collections](https://docs.ogc.org/DRAFTS/20-024.html).
     * OGC API Collections List
     */
    async collectionsRaw(requestParameters: CollectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Collections>> {
        const requestOptions = await this.collectionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionsFromJSON(jsonValue));
    }

    /**
     * Cf. [OGC API - Common - Part 2: Collections](https://docs.ogc.org/DRAFTS/20-024.html).
     * OGC API Collections List
     */
    async collections(requestParameters: CollectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Collections> {
        const response = await this.collectionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for conformance without sending the request
     */
    async conformanceRequestOpts(requestParameters: ConformanceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['processingGraphId'] == null) {
            throw new runtime.RequiredError(
                'processingGraphId',
                'Required parameter "processingGraphId" was null or undefined when calling conformance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ogc/ogc/{processingGraphId}/conformance`;
        urlPath = urlPath.replace(`{${"processingGraphId"}}`, encodeURIComponent(String(requestParameters['processingGraphId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cf. [OGC API - Common - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html).
     * OGC API Conformance Classes
     */
    async conformanceRaw(requestParameters: ConformanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Conformance>> {
        const requestOptions = await this.conformanceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConformanceFromJSON(jsonValue));
    }

    /**
     * Cf. [OGC API - Common - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html).
     * OGC API Conformance Classes
     */
    async conformance(requestParameters: ConformanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Conformance> {
        const response = await this.conformanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for landingPage without sending the request
     */
    async landingPageRequestOpts(requestParameters: LandingPageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['processingGraphId'] == null) {
            throw new runtime.RequiredError(
                'processingGraphId',
                'Required parameter "processingGraphId" was null or undefined when calling landingPage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ogc/ogc/{processingGraphId}/`;
        urlPath = urlPath.replace(`{${"processingGraphId"}}`, encodeURIComponent(String(requestParameters['processingGraphId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cf. [OGC API - Common - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html).
     * OGC API Landing Page
     */
    async landingPageRaw(requestParameters: LandingPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LandingPage>> {
        const requestOptions = await this.landingPageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LandingPageFromJSON(jsonValue));
    }

    /**
     * Cf. [OGC API - Common - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html).
     * OGC API Landing Page
     */
    async landingPage(requestParameters: LandingPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LandingPage> {
        const response = await this.landingPageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tile without sending the request
     */
    async tileRequestOpts(requestParameters: TileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['processingGraphId'] == null) {
            throw new runtime.RequiredError(
                'processingGraphId',
                'Required parameter "processingGraphId" was null or undefined when calling tile().'
            );
        }

        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling tile().'
            );
        }

        if (requestParameters['tileMatrixSetId'] == null) {
            throw new runtime.RequiredError(
                'tileMatrixSetId',
                'Required parameter "tileMatrixSetId" was null or undefined when calling tile().'
            );
        }

        if (requestParameters['tileMatrix'] == null) {
            throw new runtime.RequiredError(
                'tileMatrix',
                'Required parameter "tileMatrix" was null or undefined when calling tile().'
            );
        }

        if (requestParameters['tileRow'] == null) {
            throw new runtime.RequiredError(
                'tileRow',
                'Required parameter "tileRow" was null or undefined when calling tile().'
            );
        }

        if (requestParameters['tileCol'] == null) {
            throw new runtime.RequiredError(
                'tileCol',
                'Required parameter "tileCol" was null or undefined when calling tile().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['datetime'] != null) {
            queryParameters['datetime'] = requestParameters['datetime'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ogc/ogc/{processingGraphId}/collections/{collectionId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}`;
        urlPath = urlPath.replace(`{${"processingGraphId"}}`, encodeURIComponent(String(requestParameters['processingGraphId'])));
        urlPath = urlPath.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId'])));
        urlPath = urlPath.replace(`{${"tileMatrixSetId"}}`, encodeURIComponent(String(requestParameters['tileMatrixSetId'])));
        urlPath = urlPath.replace(`{${"tileMatrix"}}`, encodeURIComponent(String(requestParameters['tileMatrix'])));
        urlPath = urlPath.replace(`{${"tileRow"}}`, encodeURIComponent(String(requestParameters['tileRow'])));
        urlPath = urlPath.replace(`{${"tileCol"}}`, encodeURIComponent(String(requestParameters['tileCol'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cf. [OGC API - Tiles - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html).
     * OGC API Tile
     */
    async tileRaw(requestParameters: TileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.tileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Cf. [OGC API - Tiles - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html).
     * OGC API Tile
     */
    async tile(requestParameters: TileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.tileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tileMatrixSet without sending the request
     */
    async tileMatrixSetRequestOpts(requestParameters: TileMatrixSetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['processingGraphId'] == null) {
            throw new runtime.RequiredError(
                'processingGraphId',
                'Required parameter "processingGraphId" was null or undefined when calling tileMatrixSet().'
            );
        }

        if (requestParameters['tileMatrixSetId'] == null) {
            throw new runtime.RequiredError(
                'tileMatrixSetId',
                'Required parameter "tileMatrixSetId" was null or undefined when calling tileMatrixSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ogc/ogc/{processingGraphId}/tileMatrixSets/{tileMatrixSetId}`;
        urlPath = urlPath.replace(`{${"processingGraphId"}}`, encodeURIComponent(String(requestParameters['processingGraphId'])));
        urlPath = urlPath.replace(`{${"tileMatrixSetId"}}`, encodeURIComponent(String(requestParameters['tileMatrixSetId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cf. [OGC API - Tiles - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html). Cf. [OGC Two Dimensional Tile Matrix Set and Tile Set Metadata](https://docs.ogc.org/is/17-083r4/17-083r4.html).
     * OGC API Tile Matrix Set Definition
     */
    async tileMatrixSetRaw(requestParameters: TileMatrixSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TileMatrixSet>> {
        const requestOptions = await this.tileMatrixSetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TileMatrixSetFromJSON(jsonValue));
    }

    /**
     * Cf. [OGC API - Tiles - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html). Cf. [OGC Two Dimensional Tile Matrix Set and Tile Set Metadata](https://docs.ogc.org/is/17-083r4/17-083r4.html).
     * OGC API Tile Matrix Set Definition
     */
    async tileMatrixSet(requestParameters: TileMatrixSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TileMatrixSet> {
        const response = await this.tileMatrixSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tileMatrixSets without sending the request
     */
    async tileMatrixSetsRequestOpts(requestParameters: TileMatrixSetsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['processingGraphId'] == null) {
            throw new runtime.RequiredError(
                'processingGraphId',
                'Required parameter "processingGraphId" was null or undefined when calling tileMatrixSets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ogc/ogc/{processingGraphId}/tileMatrixSets`;
        urlPath = urlPath.replace(`{${"processingGraphId"}}`, encodeURIComponent(String(requestParameters['processingGraphId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cf. [OGC API - Tiles - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html). Cf. [OGC Two Dimensional Tile Matrix Set and Tile Set Metadata](https://docs.ogc.org/is/17-083r4/17-083r4.html).
     * OGC API Tile Matrix Set List
     */
    async tileMatrixSetsRaw(requestParameters: TileMatrixSetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TileMatrixSets>> {
        const requestOptions = await this.tileMatrixSetsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TileMatrixSetsFromJSON(jsonValue));
    }

    /**
     * Cf. [OGC API - Tiles - Part 1: Core](https://docs.ogc.org/is/19-072/19-072.html). Cf. [OGC Two Dimensional Tile Matrix Set and Tile Set Metadata](https://docs.ogc.org/is/17-083r4/17-083r4.html).
     * OGC API Tile Matrix Set List
     */
    async tileMatrixSets(requestParameters: TileMatrixSetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TileMatrixSets> {
        const response = await this.tileMatrixSetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
