/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PermissionListing,
  PermissionRequest,
} from '../models/index';
import {
    PermissionListingFromJSON,
    PermissionListingToJSON,
    PermissionRequestFromJSON,
    PermissionRequestToJSON,
} from '../models/index';

export interface AddPermissionHandlerRequest {
    permissionRequest: PermissionRequest;
}

export interface GetResourcePermissionsHandlerRequest {
    resourceType: string;
    resourceId: string;
    limit: number;
    offset: number;
}

export interface RemovePermissionHandlerRequest {
    permissionRequest: PermissionRequest;
}

/**
 * 
 */
export class PermissionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for addPermissionHandler without sending the request
     */
    async addPermissionHandlerRequestOpts(requestParameters: AddPermissionHandlerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['permissionRequest'] == null) {
            throw new runtime.RequiredError(
                'permissionRequest',
                'Required parameter "permissionRequest" was null or undefined when calling addPermissionHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/permissions`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PermissionRequestToJSON(requestParameters['permissionRequest']),
        };
    }

    /**
     * Adds a new permission.
     */
    async addPermissionHandlerRaw(requestParameters: AddPermissionHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.addPermissionHandlerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Adds a new permission.
     */
    async addPermissionHandler(requestParameters: AddPermissionHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addPermissionHandlerRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getResourcePermissionsHandler without sending the request
     */
    async getResourcePermissionsHandlerRequestOpts(requestParameters: GetResourcePermissionsHandlerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resourceType'] == null) {
            throw new runtime.RequiredError(
                'resourceType',
                'Required parameter "resourceType" was null or undefined when calling getResourcePermissionsHandler().'
            );
        }

        if (requestParameters['resourceId'] == null) {
            throw new runtime.RequiredError(
                'resourceId',
                'Required parameter "resourceId" was null or undefined when calling getResourcePermissionsHandler().'
            );
        }

        if (requestParameters['limit'] == null) {
            throw new runtime.RequiredError(
                'limit',
                'Required parameter "limit" was null or undefined when calling getResourcePermissionsHandler().'
            );
        }

        if (requestParameters['offset'] == null) {
            throw new runtime.RequiredError(
                'offset',
                'Required parameter "offset" was null or undefined when calling getResourcePermissionsHandler().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/permissions/resources/{resource_type}/{resource_id}`;
        urlPath = urlPath.replace(`{${"resource_type"}}`, encodeURIComponent(String(requestParameters['resourceType'])));
        urlPath = urlPath.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters['resourceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists permission for a given resource.
     */
    async getResourcePermissionsHandlerRaw(requestParameters: GetResourcePermissionsHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PermissionListing>>> {
        const requestOptions = await this.getResourcePermissionsHandlerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PermissionListingFromJSON));
    }

    /**
     * Lists permission for a given resource.
     */
    async getResourcePermissionsHandler(requestParameters: GetResourcePermissionsHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PermissionListing>> {
        const response = await this.getResourcePermissionsHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removePermissionHandler without sending the request
     */
    async removePermissionHandlerRequestOpts(requestParameters: RemovePermissionHandlerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['permissionRequest'] == null) {
            throw new runtime.RequiredError(
                'permissionRequest',
                'Required parameter "permissionRequest" was null or undefined when calling removePermissionHandler().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/permissions`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: PermissionRequestToJSON(requestParameters['permissionRequest']),
        };
    }

    /**
     * Removes an existing permission.
     */
    async removePermissionHandlerRaw(requestParameters: RemovePermissionHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removePermissionHandlerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes an existing permission.
     */
    async removePermissionHandler(requestParameters: RemovePermissionHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removePermissionHandlerRaw(requestParameters, initOverrides);
    }

}
