/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WrappedPlotOutput,
} from '../models/index';
import {
    WrappedPlotOutputFromJSON,
    WrappedPlotOutputToJSON,
} from '../models/index';

export interface GetPlotHandlerRequest {
    bbox: string;
    time: string;
    spatialResolution: string;
    id: string;
    crs?: string | null;
}

/**
 * 
 */
export class PlotsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPlotHandler without sending the request
     */
    async getPlotHandlerRequestOpts(requestParameters: GetPlotHandlerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bbox'] == null) {
            throw new runtime.RequiredError(
                'bbox',
                'Required parameter "bbox" was null or undefined when calling getPlotHandler().'
            );
        }

        if (requestParameters['time'] == null) {
            throw new runtime.RequiredError(
                'time',
                'Required parameter "time" was null or undefined when calling getPlotHandler().'
            );
        }

        if (requestParameters['spatialResolution'] == null) {
            throw new runtime.RequiredError(
                'spatialResolution',
                'Required parameter "spatialResolution" was null or undefined when calling getPlotHandler().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPlotHandler().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['crs'] != null) {
            queryParameters['crs'] = requestParameters['crs'];
        }

        if (requestParameters['time'] != null) {
            queryParameters['time'] = requestParameters['time'];
        }

        if (requestParameters['spatialResolution'] != null) {
            queryParameters['spatialResolution'] = requestParameters['spatialResolution'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/plot/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * # Example  1. Upload the file `plain_data.csv` with the following content:  ```csv a 1 2 ``` 2. Create a dataset from it using the \"Plain Data\" example at `/dataset`. 3. Create a statistics workflow using the \"Statistics Plot\" example at `/workflow`. 4. Generate the plot with this handler.
     * Generates a plot.
     */
    async getPlotHandlerRaw(requestParameters: GetPlotHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WrappedPlotOutput>> {
        const requestOptions = await this.getPlotHandlerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WrappedPlotOutputFromJSON(jsonValue));
    }

    /**
     * # Example  1. Upload the file `plain_data.csv` with the following content:  ```csv a 1 2 ``` 2. Create a dataset from it using the \"Plain Data\" example at `/dataset`. 3. Create a statistics workflow using the \"Statistics Plot\" example at `/workflow`. 4. Generate the plot with this handler.
     * Generates a plot.
     */
    async getPlotHandler(requestParameters: GetPlotHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WrappedPlotOutput> {
        const response = await this.getPlotHandlerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
